def get_values():
    return [{'label': 'Country',
             'key': 'country',
             'type': 'dict',
             'data': [{"key": "AF", "label": "Afghanistan"}, {"key": "AX", "label": "\u00c5land Islands"},
                      {"key": "AL", "label": "Albania"}, {"key": "DZ", "label": "Algeria"},
                      {"key": "AS", "label": "American Samoa"}, {"key": "AD", "label": "Andorra"},
                      {"key": "AO", "label": "Angola"}, {"key": "AI", "label": "Anguilla"},
                      {"key": "AQ", "label": "Antarctica"}, {"key": "AG", "label": "Antigua and Barbuda"},
                      {"key": "AR", "label": "Argentina"}, {"key": "AM", "label": "Armenia"},
                      {"key": "AW", "label": "Aruba"}, {"key": "AU", "label": "Australia"},
                      {"key": "AT", "label": "Austria"}, {"key": "AZ", "label": "Azerbaijan"},
                      {"key": "BS", "label": "Bahamas"}, {"key": "BH", "label": "Bahrain"},
                      {"key": "BD", "label": "Bangladesh"}, {"key": "BB", "label": "Barbados"},
                      {"key": "BY", "label": "Belarus"}, {"key": "BE", "label": "Belgium"},
                      {"key": "BZ", "label": "Belize"}, {"key": "BJ", "label": "Benin"},
                      {"key": "BM", "label": "Bermuda"}, {"key": "BT", "label": "Bhutan"},
                      {"key": "BO", "label": "Bolivia, Plurinational State of"},
                      {"key": "BQ", "label": "Bonaire, Sint Eustatius and Saba"},
                      {"key": "BA", "label": "Bosnia and Herzegovina"}, {"key": "BW", "label": "Botswana"},
                      {"key": "BV", "label": "Bouvet Island"}, {"key": "BR", "label": "Brazil"},
                      {"key": "IO", "label": "British Indian Ocean Territory"},
                      {"key": "BN", "label": "Brunei Darussalam"}, {"key": "BG", "label": "Bulgaria"},
                      {"key": "BF", "label": "Burkina Faso"}, {"key": "BI", "label": "Burundi"},
                      {"key": "KH", "label": "Cambodia"}, {"key": "CM", "label": "Cameroon"},
                      {"key": "CA", "label": "Canada"}, {"key": "CV", "label": "Cape Verde"},
                      {"key": "KY", "label": "Cayman Islands"}, {"key": "CF", "label": "Central African Republic"},
                      {"key": "TD", "label": "Chad"}, {"key": "CL", "label": "Chile"},
                      {"key": "CN", "label": "China"}, {"key": "CX", "label": "Christmas Island"},
                      {"key": "CC", "label": "Cocos (Keeling) Islands"}, {"key": "CO", "label": "Colombia"},
                      {"key": "KM", "label": "Comoros"}, {"key": "CG", "label": "Congo"},
                      {"key": "CD", "label": "Congo, the Democratic Republic of the"},
                      {"key": "CK", "label": "Cook Islands"}, {"key": "CR", "label": "Costa Rica"},
                      {"key": "CI", "label": "C\u00f4te d'Ivoire"}, {"key": "HR", "label": "Croatia"},
                      {"key": "CU", "label": "Cuba"}, {"key": "CW", "label": "Cura\u00e7ao"},
                      {"key": "CY", "label": "Cyprus"}, {"key": "CZ", "label": "Czech Republic"},
                      {"key": "DK", "label": "Denmark"}, {"key": "DJ", "label": "Djibouti"},
                      {"key": "DM", "label": "Dominica"}, {"key": "DO", "label": "Dominican Republic"},
                      {"key": "EC", "label": "Ecuador"}, {"key": "EG", "label": "Egypt"},
                      {"key": "SV", "label": "El Salvador"}, {"key": "GQ", "label": "Equatorial Guinea"},
                      {"key": "ER", "label": "Eritrea"}, {"key": "EE", "label": "Estonia"},
                      {"key": "ET", "label": "Ethiopia"}, {"key": "FK", "label": "Falkland Islands (Malvinas)"},
                      {"key": "FO", "label": "Faroe Islands"}, {"key": "FJ", "label": "Fiji"},
                      {"key": "FI", "label": "Finland"}, {"key": "FR", "label": "France"},
                      {"key": "GF", "label": "French Guiana"}, {"key": "PF", "label": "French Polynesia"},
                      {"key": "TF", "label": "French Southern Territories"}, {"key": "GA", "label": "Gabon"},
                      {"key": "GM", "label": "Gambia"}, {"key": "GE", "label": "Georgia"},
                      {"key": "DE", "label": "Germany"}, {"key": "GH", "label": "Ghana"},
                      {"key": "GI", "label": "Gibraltar"}, {"key": "GR", "label": "Greece"},
                      {"key": "GL", "label": "Greenland"}, {"key": "GD", "label": "Grenada"},
                      {"key": "GP", "label": "Guadeloupe"}, {"key": "GU", "label": "Guam"},
                      {"key": "GT", "label": "Guatemala"}, {"key": "GG", "label": "Guernsey"},
                      {"key": "GN", "label": "Guinea"}, {"key": "GW", "label": "Guinea-Bissau"},
                      {"key": "GY", "label": "Guyana"}, {"key": "HT", "label": "Haiti"},
                      {"key": "HM", "label": "Heard Island and McDonald Islands"},
                      {"key": "VA", "label": "Holy See (Vatican City State)"}, {"key": "HN", "label": "Honduras"},
                      {"key": "HK", "label": "Hong Kong"}, {"key": "HU", "label": "Hungary"},
                      {"key": "IS", "label": "Iceland"}, {"key": "IN", "label": "India"},
                      {"key": "ID", "label": "Indonesia"}, {"key": "IR", "label": "Iran, Islamic Republic of"},
                      {"key": "IQ", "label": "Iraq"}, {"key": "IE", "label": "Ireland"},
                      {"key": "IM", "label": "Isle of Man"}, {"key": "IL", "label": "Israel"},
                      {"key": "IT", "label": "Italy"}, {"key": "JM", "label": "Jamaica"},
                      {"key": "JP", "label": "Japan"}, {"key": "JE", "label": "Jersey"},
                      {"key": "JO", "label": "Jordan"}, {"key": "KZ", "label": "Kazakhstan"},
                      {"key": "KE", "label": "Kenya"}, {"key": "KI", "label": "Kiribati"},
                      {"key": "KP", "label": "Korea, Democratic People's Republic of"},
                      {"key": "KR", "label": "Korea, Republic of"}, {"key": "KW", "label": "Kuwait"},
                      {"key": "KG", "label": "Kyrgyzstan"},
                      {"key": "LA", "label": "Lao People's Democratic Republic"}, {"key": "LV", "label": "Latvia"},
                      {"key": "LB", "label": "Lebanon"}, {"key": "LS", "label": "Lesotho"},
                      {"key": "LR", "label": "Liberia"}, {"key": "LY", "label": "Libya"},
                      {"key": "LI", "label": "Liechtenstein"}, {"key": "LT", "label": "Lithuania"},
                      {"key": "LU", "label": "Luxembourg"}, {"key": "MO", "label": "Macao"},
                      {"key": "MK", "label": "Macedonia, the Former Yugoslav Republic of"},
                      {"key": "MG", "label": "Madagascar"}, {"key": "MW", "label": "Malawi"},
                      {"key": "MY", "label": "Malaysia"}, {"key": "MV", "label": "Maldives"},
                      {"key": "ML", "label": "Mali"}, {"key": "MT", "label": "Malta"},
                      {"key": "MH", "label": "Marshall Islands"}, {"key": "MQ", "label": "Martinique"},
                      {"key": "MR", "label": "Mauritania"}, {"key": "MU", "label": "Mauritius"},
                      {"key": "YT", "label": "Mayotte"}, {"key": "MX", "label": "Mexico"},
                      {"key": "FM", "label": "Micronesia, Federated States of"},
                      {"key": "MD", "label": "Moldova, Republic of"}, {"key": "MC", "label": "Monaco"},
                      {"key": "MN", "label": "Mongolia"}, {"key": "ME", "label": "Montenegro"},
                      {"key": "MS", "label": "Montserrat"}, {"key": "MA", "label": "Morocco"},
                      {"key": "MZ", "label": "Mozambique"}, {"key": "MM", "label": "Myanmar"},
                      {"key": "NA", "label": "Namibia"}, {"key": "NR", "label": "Nauru"},
                      {"key": "NP", "label": "Nepal"}, {"key": "NL", "label": "Netherlands"},
                      {"key": "NC", "label": "New Caledonia"}, {"key": "NZ", "label": "New Zealand"},
                      {"key": "NI", "label": "Nicaragua"}, {"key": "NE", "label": "Niger"},
                      {"key": "NG", "label": "Nigeria"}, {"key": "NU", "label": "Niue"},
                      {"key": "NF", "label": "Norfolk Island"}, {"key": "MP", "label": "Northern Mariana Islands"},
                      {"key": "NO", "label": "Norway"}, {"key": "OM", "label": "Oman"},
                      {"key": "PK", "label": "Pakistan"}, {"key": "PW", "label": "Palau"},
                      {"key": "PS", "label": "Palestine, State of"}, {"key": "PA", "label": "Panama"},
                      {"key": "PG", "label": "Papua New Guinea"}, {"key": "PY", "label": "Paraguay"},
                      {"key": "PE", "label": "Peru"}, {"key": "PH", "label": "Philippines"},
                      {"key": "PN", "label": "Pitcairn"}, {"key": "PL", "label": "Poland"},
                      {"key": "PT", "label": "Portugal"}, {"key": "PR", "label": "Puerto Rico"},
                      {"key": "QA", "label": "Qatar"}, {"key": "RE", "label": "R\u00e9union"},
                      {"key": "RO", "label": "Romania"}, {"key": "RU", "label": "Russian Federation"},
                      {"key": "RW", "label": "Rwanda"}, {"key": "BL", "label": "Saint Barth\u00e9lemy"},
                      {"key": "SH", "label": "Saint Helena, Ascension and Tristan da Cunha"},
                      {"key": "KN", "label": "Saint Kitts and Nevis"}, {"key": "LC", "label": "Saint Lucia"},
                      {"key": "MF", "label": "Saint Martin (French part)"},
                      {"key": "PM", "label": "Saint Pierre and Miquelon"},
                      {"key": "VC", "label": "Saint Vincent and the Grenadines"}, {"key": "WS", "label": "Samoa"},
                      {"key": "SM", "label": "San Marino"}, {"key": "ST", "label": "Sao Tome and Principe"},
                      {"key": "SA", "label": "Saudi Arabia"}, {"key": "SN", "label": "Senegal"},
                      {"key": "RS", "label": "Serbia"}, {"key": "SC", "label": "Seychelles"},
                      {"key": "SL", "label": "Sierra Leone"}, {"key": "SG", "label": "Singapore"},
                      {"key": "SX", "label": "Sint Maarten (Dutch part)"}, {"key": "SK", "label": "Slovakia"},
                      {"key": "SI", "label": "Slovenia"}, {"key": "SB", "label": "Solomon Islands"},
                      {"key": "SO", "label": "Somalia"}, {"key": "ZA", "label": "South Africa"},
                      {"key": "GS", "label": "South Georgia and the South Sandwich Islands"},
                      {"key": "SS", "label": "South Sudan"}, {"key": "ES", "label": "Spain"},
                      {"key": "LK", "label": "Sri Lanka"}, {"key": "SD", "label": "Sudan"},
                      {"key": "SR", "label": "Surilabel"}, {"key": "SJ", "label": "Svalbard and Jan Mayen"},
                      {"key": "SZ", "label": "Swaziland"}, {"key": "SE", "label": "Sweden"},
                      {"key": "CH", "label": "Switzerland"}, {"key": "SY", "label": "Syrian Arab Republic"},
                      {"key": "TW", "label": "Taiwan, Province of China"}, {"key": "TJ", "label": "Tajikistan"},
                      {"key": "TZ", "label": "Tanzania, United Republic of"}, {"key": "TH", "label": "Thailand"},
                      {"key": "TL", "label": "Timor-Leste"}, {"key": "TG", "label": "Togo"},
                      {"key": "TK", "label": "Tokelau"}, {"key": "TO", "label": "Tonga"},
                      {"key": "TT", "label": "Trinidad and Tobago"}, {"key": "TN", "label": "Tunisia"},
                      {"key": "TR", "label": "Turkey"}, {"key": "TM", "label": "Turkmenistan"},
                      {"key": "TC", "label": "Turks and Caicos Islands"}, {"key": "TV", "label": "Tuvalu"},
                      {"key": "UG", "label": "Uganda"}, {"key": "UA", "label": "Ukraine"},
                      {"key": "AE", "label": "United Arab Emirates"}, {"key": "GB", "label": "United Kingdom"},
                      {"key": "US", "label": "United States"},
                      {"key": "UM", "label": "United States Minor Outlying Islands"},
                      {"key": "UY", "label": "Uruguay"}, {"key": "UZ", "label": "Uzbekistan"},
                      {"key": "VU", "label": "Vanuatu"},
                      {"key": "VE", "label": "Venezuela, Bolivarian Republic of"},
                      {"key": "VN", "label": "Viet Nam"}, {"key": "VG", "label": "Virgin Islands, British"},
                      {"key": "VI", "label": "Virgin Islands, U.S."}, {"key": "WF", "label": "Wallis and Futuna"},
                      {"key": "EH", "label": "Western Sahara"}, {"key": "YE", "label": "Yemen"},
                      {"key": "ZM", "label": "Zambia"}, {"key": "ZW", "label": "Zimbabwe"}]
             },
            {'label': 'Device type', 'key': 'deviceType',
             'type': 'dict',
             'data': [{'key': 'car_entertainment_system', 'label': 'Car Entertainment System'},
                      {'key': 'console', 'label': 'Console'}, {'key': 'desktop', 'label': 'Desktop'},
                      {'key': 'digital_camera', 'label': 'Digital Camera'},
                      {'key': 'ebook_reader', 'label': 'Ebook Reader'},
                      {'key': 'mobile_device', 'label': 'Mobile Device'},
                      {'key': 'mobile_phone', 'label': 'Mobile Phone'},
                      {'key': 'tv_device', 'label': 'TV Device'}, {'key': 'tablet', 'label': 'Tablet'}]},
            {'label': 'JavaScript', 'key': 'javascript',
             'type': 'bool'},
            {'label': 'Operating System', 'key': 'platform',
             'type': 'dict',
             'data': [{'key': 'aix', 'label': 'AIX'}, {'key': 'atv_os_x', 'label': 'ATV OS X'},
                      {'key': 'amiga_os', 'label': 'Amiga OS'}, {'key': 'android', 'label': 'Android'},
                      {'key': 'android_for_googletv', 'label': 'Android for GoogleTV'},
                      {'key': 'asha', 'label': 'Asha'}, {'key': 'bsd', 'label': 'BSD'},
                      {'key': 'bada', 'label': 'Bada'}, {'key': 'beos', 'label': 'BeOS'},
                      {'key': 'brew', 'label': 'Brew'}, {'key': 'brew_mp', 'label': 'Brew MP'},
                      {'key': 'cellos', 'label': 'CellOS'}, {'key': 'centos', 'label': 'CentOS'},
                      {'key': 'chromeos', 'label': 'ChromeOS'},
                      {'key': 'chromecast_os', 'label': 'Chromecast OS'},
                      {'key': 'cygwin', 'label': 'CygWin'}, {'key': 'darwin', 'label': 'Darwin'},
                      {'key': 'debian', 'label': 'Debian'},
                      {'key': 'dragonfly_bsd', 'label': 'DragonFly BSD'},
                      {'key': 'fedora', 'label': 'Fedora'}, {'key': 'firefoxos', 'label': 'FirefoxOS'},
                      {'key': 'freebsd', 'label': 'FreeBSD'}, {'key': 'hp-ux', 'label': 'HP-UX'},
                      {'key': 'haiku', 'label': 'Haiku'}, {'key': 'irix64', 'label': 'IRIX64'},
                      {'key': 'inferno_os', 'label': 'Inferno OS'}, {'key': 'java', 'label': 'JAVA'},
                      {'key': 'kaios', 'label': 'KaiOS'}, {'key': 'linux', 'label': 'Linux'},
                      {'key': 'maui', 'label': 'MAUI'}, {'key': 'mac68k', 'label': 'Mac68K'},
                      {'key': 'macosx', 'label': 'MacOSX'}, {'key': 'macppc', 'label': 'MacPPC'},
                      {'key': 'maemo', 'label': 'Maemo'}, {'key': 'meego', 'label': 'MeeGo'},
                      {'key': 'miui_os', 'label': 'Miui OS'}, {'key': 'mobilinux', 'label': 'Mobilinux'},
                      {'key': 'netbsd', 'label': 'NetBSD'},
                      {'key': 'nintendo_3ds', 'label': 'Nintendo 3DS'},
                      {'key': 'nintendo_ds', 'label': 'Nintendo DS'},
                      {'key': 'nintendo_dsi', 'label': 'Nintendo DSi'},
                      {'key': 'nintendo_switch', 'label': 'Nintendo Switch'},
                      {'key': 'nintendo_wii', 'label': 'Nintendo Wii'},
                      {'key': 'nintendo_wiiu', 'label': 'Nintendo WiiU'}, {'key': 'os/2', 'label': 'OS/2'},
                      {'key': 'openbsd', 'label': 'OpenBSD'}, {'key': 'openvms', 'label': 'OpenVMS'},
                      {'key': 'orbisos', 'label': 'OrbisOS'}, {'key': 'palmos', 'label': 'PalmOS'},
                      {'key': 'playstation_vita', 'label': 'Playstation Vita'},
                      {'key': 'rim_os', 'label': 'RIM OS'},
                      {'key': 'rim_tablet_os', 'label': 'RIM Tablet OS'},
                      {'key': 'risc_os', 'label': 'RISC OS'}, {'key': 'red_hat', 'label': 'Red Hat'},
                      {'key': 'sailfishos', 'label': 'SailfishOS'},
                      {'key': 'series30', 'label': 'Series30'}, {'key': 'series40', 'label': 'Series40'},
                      {'key': 'solaris', 'label': 'Solaris'}, {'key': 'sunos', 'label': 'SunOS'},
                      {'key': 'syllable', 'label': 'Syllable'}, {'key': 'symbianos', 'label': 'SymbianOS'},
                      {'key': 'tizen', 'label': 'Tizen'}, {'key': 'tru64_unix', 'label': 'Tru64 UNIX'},
                      {'key': 'ubuntu', 'label': 'Ubuntu'},
                      {'key': 'ubuntu_touch', 'label': 'Ubuntu Touch'}, {'key': 'unix', 'label': 'Unix'},
                      {'key': 'win10', 'label': 'Win10'}, {'key': 'win16', 'label': 'Win16'},
                      {'key': 'win2000', 'label': 'Win2000'}, {'key': 'win31', 'label': 'Win31'},
                      {'key': 'win32', 'label': 'Win32'}, {'key': 'win64', 'label': 'Win64'},
                      {'key': 'win7', 'label': 'Win7'}, {'key': 'win8', 'label': 'Win8'},
                      {'key': 'win8.1', 'label': 'Win8.1'}, {'key': 'win95', 'label': 'Win95'},
                      {'key': 'win98', 'label': 'Win98'}, {'key': 'wince', 'label': 'WinCE'},
                      {'key': 'winme', 'label': 'WinME'}, {'key': 'winmobile', 'label': 'WinMobile'},
                      {'key': 'winnt', 'label': 'WinNT'}, {'key': 'winphone', 'label': 'WinPhone'},
                      {'key': 'winphone10', 'label': 'WinPhone10'},
                      {'key': 'winphone6', 'label': 'WinPhone6'},
                      {'key': 'winphone7', 'label': 'WinPhone7'},
                      {'key': 'winphone7.5', 'label': 'WinPhone7.5'},
                      {'key': 'winphone7.8', 'label': 'WinPhone7.8'},
                      {'key': 'winphone8', 'label': 'WinPhone8'},
                      {'key': 'winphone8.1', 'label': 'WinPhone8.1'}, {'key': 'winrt8', 'label': 'WinRT8'},
                      {'key': 'winrt8.1', 'label': 'WinRT8.1'}, {'key': 'winvista', 'label': 'WinVista'},
                      {'key': 'winxp', 'label': 'WinXP'}, {'key': 'xbox_360', 'label': 'Xbox 360'},
                      {'key': 'xbox_360_(mobile_view)', 'label': 'Xbox 360 (Mobile View)'},
                      {'key': 'xbox_os', 'label': 'Xbox OS'},
                      {'key': 'xbox_os_(mobile_view)', 'label': 'Xbox OS (Mobile View)'},
                      {'key': 'xbox_os_10', 'label': 'Xbox OS 10'},
                      {'key': 'xbox_os_10_(mobile_view)', 'label': 'Xbox OS 10 (Mobile View)'},
                      {'key': 'ios', 'label': 'iOS'}, {'key': 'macos', 'label': 'macOS'},
                      {'key': 'webos', 'label': 'webOS'}]},
            {'label': 'Browser', 'key': 'browser',
             'type': 'dict',
             'data': [{'key': '115_browser', 'label': '115 Browser'},
                      {'key': '1password', 'label': '1Password'},
                      {'key': '1passwordthumbs', 'label': '1PasswordThumbs'},
                      {'key': '1stbrowser', 'label': '1stBrowser'},
                      {'key': '2345_browser', 'label': '2345 Browser'},
                      {'key': '2345_chrome', 'label': '2345 Chrome'},
                      {'key': '2345_explorer', 'label': '2345 Explorer'},
                      {'key': '360_secure_browser', 'label': '360 Secure Browser'},
                      {'key': '360_speed_browser', 'label': '360 Speed Browser'},
                      {'key': '37abc', 'label': '37abc'}, {'key': '7_star', 'label': '7 Star'},
                      {'key': '77_wabc', 'label': '77 WABC'}, {'key': 'abrowse', 'label': 'ABrowse'},
                      {'key': 'ant_galio', 'label': 'ANT Galio'}, {'key': 'aol_app', 'label': 'AOL App'},
                      {'key': 'aol_desktop', 'label': 'AOL Desktop'},
                      {'key': 'aol_shield', 'label': 'AOL Shield'},
                      {'key': 'apusbrowser', 'label': 'APUSBrowser'}, {'key': 'attws', 'label': 'ATTWS'},
                      {'key': 'au', 'label': 'AU'}, {'key': 'access', 'label': 'Access'},
                      {'key': 'acoo_browser', 'label': 'Acoo Browser'},
                      {'key': 'adobe_air', 'label': 'Adobe AIR'}, {'key': 'airmail', 'label': 'Airmail'},
                      {'key': 'alcatel', 'label': 'Alcatel'},
                      {'key': 'alexa_mediaplayer', 'label': 'Alexa MediaPlayer'},
                      {'key': 'aliapp', 'label': 'AliApp'}, {'key': 'alienforce', 'label': 'Alienforce'},
                      {'key': 'alltop_app', 'label': 'Alltop App'},
                      {'key': 'aloha_browser', 'label': 'Aloha Browser'},
                      {'key': 'amarok', 'label': 'Amarok'}, {'key': 'amaya', 'label': 'Amaya'},
                      {'key': 'amigo', 'label': 'Amigo'}, {'key': 'amoi', 'label': 'Amoi'},
                      {'key': 'android', 'label': 'Android'},
                      {'key': 'android_download_manager', 'label': 'Android Download Manager'},
                      {'key': 'android_webview', 'label': 'Android WebView'},
                      {'key': 'antennapod', 'label': 'AntennaPod'},
                      {'key': 'apple_appstore_app', 'label': 'Apple AppStore App'},
                      {'key': 'apple_mail', 'label': 'Apple Mail'},
                      {'key': 'apple_news', 'label': 'Apple News'},
                      {'key': 'apple_pubsub', 'label': 'Apple PubSub'},
                      {'key': 'applecoremedia', 'label': 'AppleCoreMedia'},
                      {'key': 'argclrint', 'label': 'ArgClrInt'}, {'key': 'arora', 'label': 'Arora'},
                      {'key': 'asus', 'label': 'Asus'}, {'key': 'atomic_browser', 'label': 'Atomic Browser'},
                      {'key': 'audioboom', 'label': 'AudioBoom'}, {'key': 'automator', 'label': 'Automator'},
                      {'key': 'avant', 'label': 'Avant'},
                      {'key': 'avast_safezone', 'label': 'Avast SafeZone'},
                      {'key': 'avira_scout', 'label': 'Avira Scout'}, {'key': 'b-line', 'label': 'B-Line'},
                      {'key': 'bb2c', 'label': 'BB2C'}, {'key': 'bird', 'label': 'BIRD'},
                      {'key': 'baidu_box_app', 'label': 'Baidu Box App'},
                      {'key': 'baidu_browser', 'label': 'Baidu Browser'},
                      {'key': 'baidu_browser_hd', 'label': 'Baidu Browser HD'},
                      {'key': 'baidu_browser_mini', 'label': 'Baidu Browser Mini'},
                      {'key': 'banshee_media_player', 'label': 'Banshee Media Player'},
                      {'key': 'barca_mail_client', 'label': 'Barca Mail Client'},
                      {'key': 'bashpodder', 'label': 'BashPodder'},
                      {'key': 'battle.net_overlay', 'label': 'Battle.net Overlay'},
                      {'key': 'beamrise', 'label': 'Beamrise'}, {'key': 'bellwave', 'label': 'Bellwave'},
                      {'key': 'benq', 'label': 'BenQ'},
                      {'key': 'beonex_communicator', 'label': 'Beonex Communicator'},
                      {'key': 'beyondpod', 'label': 'BeyondPod'},
                      {'key': 'bigslickgofish', 'label': 'BigSlickGoFish'}, {'key': 'bing', 'label': 'Bing'},
                      {'key': 'bing_search_app', 'label': 'Bing Search App'},
                      {'key': 'bing_ipad', 'label': 'Bing iPad'},
                      {'key': 'blackberry', 'label': 'BlackBerry'},
                      {'key': 'blackberry_playbook_tablet', 'label': 'Blackberry Playbook Tablet'},
                      {'key': 'blackhawk', 'label': 'Blackhawk'}, {'key': 'blazer', 'label': 'Blazer'},
                      {'key': 'blue_browser', 'label': 'Blue Browser'}, {'key': 'bolt', 'label': 'Bolt'},
                      {'key': 'bowser', 'label': 'Bowser'}, {'key': 'boxee', 'label': 'Boxee'},
                      {'key': 'brave', 'label': 'Brave'}, {'key': 'browzar', 'label': 'Browzar'},
                      {'key': 'cfnetwork', 'label': 'CFNetwork'},
                      {'key': 'cm_browser', 'label': 'CM Browser'},
                      {'key': 'cmuv_dvbviewer', 'label': 'CMUV DVBViewer'}, {'key': 'ctl', 'label': 'CTL'},
                      {'key': 'camera_360', 'label': 'Camera 360'}, {'key': 'camino', 'label': 'Camino'},
                      {'key': 'cent_browser', 'label': 'Cent Browser'}, {'key': 'charon', 'label': 'Charon'},
                      {'key': 'chedot', 'label': 'Chedot'}, {'key': 'cheshire', 'label': 'Cheshire'},
                      {'key': 'chimera', 'label': 'Chimera'}, {'key': 'chrome', 'label': 'Chrome'},
                      {'key': 'chromeplus', 'label': 'ChromePlus'}, {'key': 'chromium', 'label': 'Chromium'},
                      {'key': 'classilla', 'label': 'Classilla'},
                      {'key': 'clementine', 'label': 'Clementine'}, {'key': 'clipish', 'label': 'Clipish'},
                      {'key': 'coast', 'label': 'Coast'},
                      {'key': 'coc_coc_browser', 'label': 'Coc Coc Browser'},
                      {'key': 'coda', 'label': 'Coda'}, {'key': 'cometbird', 'label': 'CometBird'},
                      {'key': 'conkeror', 'label': 'Conkeror'}, {'key': 'coolnovo', 'label': 'CoolNovo'},
                      {'key': 'cooliris', 'label': 'Cooliris'},
                      {'key': 'coursera_mobile_app', 'label': 'Coursera Mobile App'},
                      {'key': 'coverscout', 'label': 'CoverScout'},
                      {'key': 'crazy_browser', 'label': 'Crazy Browser'},
                      {'key': 'crosswalk_app', 'label': 'Crosswalk App'},
                      {'key': 'crowsnest_mobile_app', 'label': 'Crowsnest Mobile App'},
                      {'key': 'cunaguaro', 'label': 'Cunaguaro'}, {'key': 'custom', 'label': 'Custom'},
                      {'key': 'cybeye', 'label': 'CybEye'}, {'key': 'cyberdog', 'label': 'Cyberdog'},
                      {'key': 'cyberduck', 'label': 'Cyberduck'}, {'key': 'cyberfox', 'label': 'Cyberfox'},
                      {'key': 'dbtel', 'label': 'DBTEL'}, {'key': 'dalvik', 'label': 'Dalvik'},
                      {'key': 'darwin_browser', 'label': 'Darwin Browser'}, {'key': 'daum', 'label': 'Daum'},
                      {'key': 'david_client', 'label': 'David Client'},
                      {'key': 'deepnet_explorer', 'label': 'Deepnet Explorer'},
                      {'key': 'default_browser', 'label': 'Default Browser'},
                      {'key': 'defaultproperties', 'label': 'DefaultProperties'},
                      {'key': 'diglo', 'label': 'Diglo'}, {'key': 'diigo_browser', 'label': 'Diigo Browser'},
                      {'key': 'dillo', 'label': 'Dillo'}, {'key': 'docomo', 'label': 'DoCoMo'},
                      {'key': 'doggcatcher', 'label': 'DoggCatcher'}, {'key': 'dolfin', 'label': 'Dolfin'},
                      {'key': 'doppler', 'label': 'Doppler'},
                      {'key': 'dorado_wap_browser', 'label': 'Dorado WAP Browser'},
                      {'key': 'doris', 'label': 'Doris'}, {'key': 'downcast', 'label': 'Downcast'},
                      {'key': 'dragon', 'label': 'Dragon'}, {'key': 'dreamweaver', 'label': 'Dreamweaver'},
                      {'key': 'duckduck_app', 'label': 'DuckDuck App'},
                      {'key': 'eb_iphone/ipad_app', 'label': 'EB iPhone/IPad App'},
                      {'key': 'elinks', 'label': 'ELinks'}, {'key': 'esatcom', 'label': 'ESATCOM'},
                      {'key': 'espn_downloadmanager', 'label': 'ESPN DownloadManager'},
                      {'key': 'espn_radio', 'label': 'ESPN Radio'}, {'key': 'ezos', 'label': 'EZOS'},
                      {'key': 'edge', 'label': 'Edge'}, {'key': 'edge_mobile', 'label': 'Edge Mobile'},
                      {'key': 'electron', 'label': 'Electron'},
                      {'key': 'element_browser', 'label': 'Element Browser'},
                      {'key': 'elluminate_live', 'label': 'Elluminate Live'},
                      {'key': 'elmedia_player', 'label': 'Elmedia Player'},
                      {'key': 'emacs/w3', 'label': 'Emacs/W3'}, {'key': 'epic', 'label': 'Epic'},
                      {'key': 'epiphany', 'label': 'Epiphany'},
                      {'key': 'espial_tv_browser', 'label': 'Espial TV Browser'},
                      {'key': 'eudora', 'label': 'Eudora'}, {'key': 'eudora_ose', 'label': 'Eudora OSE'},
                      {'key': 'eudoraweb', 'label': 'EudoraWeb'},
                      {'key': 'evernote_app', 'label': 'Evernote App'},
                      {'key': 'evolution', 'label': 'Evolution'}, {'key': 'excel', 'label': 'Excel'},
                      {'key': 'exoplayerdemo', 'label': 'ExoPlayerDemo'},
                      {'key': 'extras4imovie', 'label': 'Extras4iMovie'}, {'key': 'fly', 'label': 'FLY'},
                      {'key': 'facebook_app', 'label': 'Facebook App'},
                      {'key': 'facebook_groups', 'label': 'Facebook Groups'},
                      {'key': 'facebook_messenger', 'label': 'Facebook Messenger'},
                      {'key': 'facebook_pages_admin', 'label': 'Facebook Pages Admin'},
                      {'key': 'fancymusic', 'label': 'FancyMusic'},
                      {'key': 'fastbrowser', 'label': 'FastBrowser'},
                      {'key': 'feeddler_rss_reader', 'label': 'Feeddler RSS Reader'},
                      {'key': 'fennec', 'label': 'Fennec'}, {'key': 'firebird', 'label': 'Firebird'},
                      {'key': 'firefox', 'label': 'Firefox'},
                      {'key': 'firefox_focus', 'label': 'Firefox Focus'},
                      {'key': 'firefox_for_ios', 'label': 'Firefox for iOS'},
                      {'key': 'flipboard_app', 'label': 'Flipboard App'},
                      {'key': 'flixster_app', 'label': 'Flixster App'}, {'key': 'flock', 'label': 'Flock'},
                      {'key': 'fluid', 'label': 'Fluid'}, {'key': 'flyflow', 'label': 'FlyFlow'},
                      {'key': 'fossamail', 'label': 'FossaMail'}, {'key': 'foxconn', 'label': 'Foxconn'},
                      {'key': 'framabird', 'label': 'Framabird'},
                      {'key': 'free-podcasts', 'label': 'Free-Podcasts'},
                      {'key': 'freebox_browser', 'label': 'Freebox Browser'},
                      {'key': 'frontpage', 'label': 'FrontPage'}, {'key': 'geo', 'label': 'GEO'},
                      {'key': 'gspda', 'label': 'GSPDA'}, {'key': 'gsmart', 'label': 'GSmart'},
                      {'key': 'galeon', 'label': 'Galeon'}, {'key': 'goldenpod', 'label': 'GoldenPod'},
                      {'key': 'goodreader', 'label': 'GoodReader'},
                      {'key': 'google_app', 'label': 'Google App'},
                      {'key': 'google_desktop', 'label': 'Google Desktop'},
                      {'key': 'google_earth', 'label': 'Google Earth'},
                      {'key': 'google_mail', 'label': 'Google Mail'},
                      {'key': 'google+_app', 'label': 'Google+ App'},
                      {'key': 'hp_secure_web_browser', 'label': 'HP Secure Web Browser'},
                      {'key': 'hs', 'label': 'HS'}, {'key': 'haier', 'label': 'Haier'},
                      {'key': 'headless_chrome', 'label': 'Headless Chrome'},
                      {'key': 'hitpad', 'label': 'Hitpad'},
                      {'key': 'hot_hd_wallpapers', 'label': 'Hot HD Wallpapers'},
                      {'key': 'hot_wallpapers', 'label': 'Hot Wallpapers'},
                      {'key': 'huawei', 'label': 'Huawei'}, {'key': 'hyundai', 'label': 'Hyundai'},
                      {'key': 'iac', 'label': 'IAC'}, {'key': 'ibrowse', 'label': 'IBrowse'},
                      {'key': 'ie', 'label': 'IE'}, {'key': 'iemobile', 'label': 'IEMobile'},
                      {'key': 'inno', 'label': 'INNO'}, {'key': 'ixi', 'label': 'IXI'},
                      {'key': 'icecat', 'label': 'IceCat'}, {'key': 'icedragon', 'label': 'IceDragon'},
                      {'key': 'iceape', 'label': 'Iceape'}, {'key': 'icedove', 'label': 'Icedove'},
                      {'key': 'iceowl', 'label': 'Iceowl'}, {'key': 'iceweasel', 'label': 'Iceweasel'},
                      {'key': 'imagemobile', 'label': 'ImageMobile'},
                      {'key': 'incredimail', 'label': 'Incredimail'},
                      {'key': 'instagram_app', 'label': 'Instagram App'},
                      {'key': 'installatron', 'label': 'Installatron'},
                      {'key': 'iridium_browser', 'label': 'Iridium Browser'},
                      {'key': 'iron', 'label': 'Iron'}, {'key': 'iron_mobile', 'label': 'Iron Mobile'},
                      {'key': 'juzi_browser', 'label': 'JUZI Browser'},
                      {'key': 'jasmine', 'label': 'Jasmine'}, {'key': 'juice', 'label': 'Juice'},
                      {'key': 'k-meleon', 'label': 'K-Meleon'}, {'key': 'k-ninja', 'label': 'K-Ninja'},
                      {'key': 'kkman', 'label': 'KKMAN'}, {'key': 'kmlite', 'label': 'KMLite'},
                      {'key': 'kmail2', 'label': 'KMail2'}, {'key': 'knbr_680', 'label': 'KNBR 680'},
                      {'key': 'konka', 'label': 'KONKA'}, {'key': 'kamelio_app', 'label': 'Kamelio App'},
                      {'key': 'kazehakase', 'label': 'Kazehakase'}, {'key': 'keeper', 'label': 'Keeper'},
                      {'key': 'kenshoo', 'label': 'Kenshoo'}, {'key': 'kindle', 'label': 'Kindle'},
                      {'key': 'kindle_fire', 'label': 'Kindle Fire'}, {'key': 'kinoma', 'label': 'Kinoma'},
                      {'key': 'kinza', 'label': 'Kinza'}, {'key': 'klondike', 'label': 'Klondike'},
                      {'key': 'kodi_media_center', 'label': 'Kodi Media Center'},
                      {'key': 'konqueror', 'label': 'Konqueror'}, {'key': 'kontact', 'label': 'Kontact'},
                      {'key': 'kuaiso', 'label': 'Kuaiso'}, {'key': 'kurio_app', 'label': 'Kurio App'},
                      {'key': 'lg', 'label': 'LG'}, {'key': 'lg_browser', 'label': 'LG Browser'},
                      {'key': 'lenovo', 'label': 'Lenovo'}, {'key': 'libreoffice', 'label': 'LibreOffice'},
                      {'key': 'light', 'label': 'Light'}, {'key': 'lightning', 'label': 'Lightning'},
                      {'key': 'line_app', 'label': 'Line App'}, {'key': 'links', 'label': 'Links'},
                      {'key': 'listia_app', 'label': 'Listia App'},
                      {'key': 'lotus_notes', 'label': 'Lotus Notes'},
                      {'key': 'lovense_browser', 'label': 'Lovense Browser'},
                      {'key': 'lunascape', 'label': 'Lunascape'},
                      {'key': 'lycoris_desktop/lx', 'label': 'Lycoris Desktop/LX'},
                      {'key': 'lync', 'label': 'Lync'}, {'key': 'lynx', 'label': 'Lynx'},
                      {'key': 'm3gate', 'label': 'M3Gate'},
                      {'key': 'maui_wap_browser', 'label': 'MAUI Wap Browser'},
                      {'key': 'mplayer', 'label': 'MPlayer'},
                      {'key': 'mstar_browser', 'label': 'MStar Browser'},
                      {'key': 'macappstore', 'label': 'MacAppStore'},
                      {'key': 'mail_free', 'label': 'Mail Free'},
                      {'key': 'mail_master', 'label': 'Mail Master'}, {'key': 'mailbar', 'label': 'MailBar'},
                      {'key': 'mark_levin_show', 'label': 'Mark Levin Show'},
                      {'key': 'matome', 'label': 'Matome'}, {'key': 'maxon', 'label': 'Maxon'},
                      {'key': 'maxthon', 'label': 'Maxthon'},
                      {'key': 'maxthon_nitro', 'label': 'Maxthon Nitro'},
                      {'key': 'media_players', 'label': 'Media Players'},
                      {'key': 'mediago', 'label': 'MediaGo'}, {'key': 'mediamonkey', 'label': 'MediaMonkey'},
                      {'key': 'mercator', 'label': 'Mercator'}, {'key': 'mercury', 'label': 'Mercury'},
                      {'key': 'microb', 'label': 'MicroB'},
                      {'key': 'microsoft_netshow', 'label': 'Microsoft NetShow'},
                      {'key': 'midori', 'label': 'Midori'}, {'key': 'minimo', 'label': 'Minimo'},
                      {'key': 'miro', 'label': 'Miro'}, {'key': 'mitsu_browser', 'label': 'Mitsu Browser'},
                      {'key': 'miui_browser', 'label': 'Miui Browser'},
                      {'key': 'mobicip', 'label': 'Mobicip'},
                      {'key': 'mobile_safari_uiwebview', 'label': 'Mobile Safari UIWebView'},
                      {'key': 'mobileexplorer', 'label': 'MobileExplorer'},
                      {'key': 'mobileiron', 'label': 'MobileIron'},
                      {'key': 'mobilerss', 'label': 'MobileRSS'}, {'key': 'mobmail', 'label': 'Mobmail'},
                      {'key': 'model_s_browser', 'label': 'Model S Browser'},
                      {'key': 'mosaic', 'label': 'Mosaic'},
                      {'key': 'motorola_internet_browser', 'label': 'Motorola Internet Browser'},
                      {'key': 'mozilla', 'label': 'Mozilla'}, {'key': 'multizilla', 'label': 'MultiZilla'},
                      {'key': 'musicdownloader', 'label': 'MusicDownloader'},
                      {'key': 'my_internet_browser', 'label': 'My Internet Browser'},
                      {'key': 'mynews', 'label': 'MyNews'}, {'key': 'nec', 'label': 'NEC'},
                      {'key': 'naver', 'label': 'Naver'}, {'key': 'navigator', 'label': 'Navigator'},
                      {'key': 'netfront', 'label': 'NetFront'},
                      {'key': 'netfront_nx', 'label': 'NetFront NX'},
                      {'key': 'netfrontlifebrowser', 'label': 'NetFrontLifeBrowser'},
                      {'key': 'netpositive', 'label': 'NetPositive'},
                      {'key': 'netvibes_app', 'label': 'NetVibes App'}, {'key': 'netbox', 'label': 'Netbox'},
                      {'key': 'netgem_set_top_box', 'label': 'Netgem Set Top Box'},
                      {'key': 'netscape', 'label': 'Netscape'}, {'key': 'neuron', 'label': 'Neuron'},
                      {'key': 'newsarticle_app', 'label': 'NewsArticle App'},
                      {'key': 'newsfire', 'label': 'NewsFire'}, {'key': 'nichrome', 'label': 'Nichrome'},
                      {'key': 'nintendo_browser', 'label': 'Nintendo Browser'},
                      {'key': 'nokia_browser', 'label': 'Nokia Browser'},
                      {'key': 'nokia_proxy_browser', 'label': 'Nokia Proxy Browser'},
                      {'key': 'ntent', 'label': 'Ntent'}, {'key': 'obigo_q', 'label': 'Obigo Q'},
                      {'key': 'oculus_browser', 'label': 'Oculus Browser'},
                      {'key': 'odyssey_web_browser', 'label': 'Odyssey Web Browser'},
                      {'key': 'office', 'label': 'Office'},
                      {'key': 'office_syncproc', 'label': 'Office SyncProc'},
                      {'key': 'office_upload_center', 'label': 'Office Upload Center'},
                      {'key': 'offline_pages', 'label': 'Offline Pages'},
                      {'key': 'okta_mobile_app', 'label': 'Okta Mobile App'},
                      {'key': 'omniweb', 'label': 'OmniWeb'}, {'key': 'onebrowser', 'label': 'OneBrowser'},
                      {'key': 'onenote', 'label': 'OneNote'}, {'key': 'openbsd_ftp', 'label': 'OpenBSD ftp'},
                      {'key': 'openoffice', 'label': 'OpenOffice'},
                      {'key': 'openwave_mobile_browser', 'label': 'Openwave Mobile Browser'},
                      {'key': 'opera', 'label': 'Opera'}, {'key': 'opera_mini', 'label': 'Opera Mini'},
                      {'key': 'opera_mobile', 'label': 'Opera Mobile'},
                      {'key': 'opera_neon', 'label': 'Opera Neon'}, {'key': 'orca', 'label': 'Orca'},
                      {'key': 'oregano', 'label': 'Oregano'}, {'key': 'origin', 'label': 'Origin'},
                      {'key': 'otter', 'label': 'Otter'}, {'key': 'outlook', 'label': 'Outlook'},
                      {'key': 'overcast', 'label': 'Overcast'},
                      {'key': 'overwolf_browser', 'label': 'Overwolf Browser'},
                      {'key': 'perfect_browser', 'label': 'PERFECT Browser'},
                      {'key': 'palemoon', 'label': 'PaleMoon'},
                      {'key': 'palm_source', 'label': 'Palm Source'},
                      {'key': 'panasonic', 'label': 'Panasonic'},
                      {'key': 'panasonic_tv_browser', 'label': 'Panasonic TV Browser'},
                      {'key': 'pandora', 'label': 'Pandora'}, {'key': 'pantech', 'label': 'Pantech'},
                      {'key': 'peapod', 'label': 'Peapod'},
                      {'key': 'phantom_browser', 'label': 'Phantom Browser'},
                      {'key': 'phantomjs', 'label': 'PhantomJS'}, {'key': 'phoenix', 'label': 'Phoenix'},
                      {'key': 'pic_collage', 'label': 'Pic Collage'},
                      {'key': 'pinterest_app', 'label': 'Pinterest App'},
                      {'key': 'pirate_browser', 'label': 'Pirate Browser'},
                      {'key': 'player', 'label': 'Player'}, {'key': 'player_fm', 'label': 'Player FM'},
                      {'key': 'playstation', 'label': 'Playstation'},
                      {'key': 'playstation_browser', 'label': 'Playstation Browser'},
                      {'key': 'pocket_casts', 'label': 'Pocket Casts'},
                      {'key': 'pocket_pc', 'label': 'Pocket PC'},
                      {'key': 'pockettunes', 'label': 'PocketTunes'},
                      {'key': 'pocomail', 'label': 'PocoMail'},
                      {'key': 'podcruncher', 'label': 'PodCruncher'},
                      {'key': 'podwrangler', 'label': 'PodWrangler'},
                      {'key': 'podcastaddict', 'label': 'PodcastAddict'},
                      {'key': 'podcastone', 'label': 'PodcastOne'}, {'key': 'podcasts', 'label': 'Podcasts'},
                      {'key': 'podkicker', 'label': 'Podkicker'},
                      {'key': 'podkicker_classic', 'label': 'Podkicker Classic'},
                      {'key': 'podkicker_pro', 'label': 'Podkicker Pro'},
                      {'key': 'polaris', 'label': 'Polaris'}, {'key': 'polarity', 'label': 'Polarity'},
                      {'key': 'postbox', 'label': 'Postbox'}, {'key': 'powerpoint', 'label': 'PowerPoint'},
                      {'key': 'powertv', 'label': 'PowerTV'}, {'key': 'prince', 'label': 'Prince'},
                      {'key': 'prism', 'label': 'Prism'}, {'key': 'prismatic_app', 'label': 'Prismatic App'},
                      {'key': 'puffin', 'label': 'Puffin'}, {'key': 'qqbrowser', 'label': 'QQBrowser'},
                      {'key': 'qqbrowser_mini', 'label': 'QQBrowser Mini'},
                      {'key': 'qiyu_browser', 'label': 'Qiyu Browser'}, {'key': 'qt', 'label': 'Qt'},
                      {'key': 'qtwebengine', 'label': 'QtWebEngine'},
                      {'key': 'qtwebkit', 'label': 'QtWebkit'}, {'key': 'quicklook', 'label': 'QuickLook'},
                      {'key': 'quicknews', 'label': 'QuickNews'}, {'key': 'quicktime', 'label': 'QuickTime'},
                      {'key': 'quicktime_agent', 'label': 'QuickTime Agent'},
                      {'key': 'quite_rss', 'label': 'Quite RSS'}, {'key': 'quora_app', 'label': 'Quora App'},
                      {'key': 'qupzilla', 'label': 'QupZilla'},
                      {'key': 'qword_browser', 'label': 'Qword Browser'}, {'key': 'rma', 'label': 'RMA'},
                      {'key': 'rssradio', 'label': 'RSSRadio'}, {'key': 'radio', 'label': 'Radio'},
                      {'key': 'raptr', 'label': 'Raptr'}, {'key': 'readability', 'label': 'Readability'},
                      {'key': 'realplayer', 'label': 'RealPlayer'},
                      {'key': 'realplayer_downloader', 'label': 'RealPlayer Downloader'},
                      {'key': 'rebelmouse', 'label': 'RebelMouse'},
                      {'key': 'redflagdeals_mobile_app', 'label': 'RedFlagDeals Mobile App'},
                      {'key': 'reddit_app', 'label': 'Reddit App'}, {'key': 'reeder', 'label': 'Reeder'},
                      {'key': 'relax_melodies', 'label': 'Relax Melodies'},
                      {'key': 'replay', 'label': 'Replay'},
                      {'key': 'roblox_studio', 'label': 'Roblox Studio'},
                      {'key': 'roccat', 'label': 'Roccat'}, {'key': 'rockmelt', 'label': 'RockMelt'},
                      {'key': 'rocky_chatwork_mobile', 'label': 'Rocky ChatWork Mobile'},
                      {'key': 'roku_dvp', 'label': 'Roku DVP'}, {'key': 'semc', 'label': 'SEMC'},
                      {'key': 'safari', 'label': 'Safari'}, {'key': 'sagem', 'label': 'Sagem'},
                      {'key': 'sailfish_browser', 'label': 'Sailfish Browser'},
                      {'key': 'saina', 'label': 'Saina'}, {'key': 'salam_browser', 'label': 'Salam Browser'},
                      {'key': 'salesforce_app', 'label': 'SalesForce App'},
                      {'key': 'samsung', 'label': 'Samsung'},
                      {'key': 'samsung_browser', 'label': 'Samsung Browser'},
                      {'key': 'samsung_crossapp', 'label': 'Samsung CrossApp'},
                      {'key': 'samsung_mobile_browser', 'label': 'Samsung Mobile Browser'},
                      {'key': 'samsung_tv', 'label': 'Samsung TV'},
                      {'key': 'samsung_webview', 'label': 'Samsung WebView'},
                      {'key': 'sandvox', 'label': 'Sandvox'},
                      {'key': 'schoolwires_app', 'label': 'Schoolwires App'},
                      {'key': 'seamonkey', 'label': 'SeaMonkey'},
                      {'key': 'second_life_commerce_client', 'label': 'Second Life Commerce Client'},
                      {'key': 'secondlife', 'label': 'SecondLife'},
                      {'key': 'seznam_browser', 'label': 'Seznam Browser'},
                      {'key': 'sharp', 'label': 'Sharp'}, {'key': 'shiira', 'label': 'Shiira'},
                      {'key': 'shrook', 'label': 'Shrook'}, {'key': 'silk', 'label': 'Silk'},
                      {'key': 'sitecon', 'label': 'SiteCon'}, {'key': 'skyfire', 'label': 'Skyfire'},
                      {'key': 'skykid', 'label': 'Skykid'}, {'key': 'sleipnir', 'label': 'Sleipnir'},
                      {'key': 'slimboat', 'label': 'SlimBoat'},
                      {'key': 'slimbrowser', 'label': 'SlimBrowser'},
                      {'key': 'slimjet_browser', 'label': 'SlimJet Browser'},
                      {'key': 'slimerjs', 'label': 'SlimerJS'},
                      {'key': 'smarttv_webbrowser', 'label': 'SmartTV WebBrowser'},
                      {'key': 'smartviera', 'label': 'SmartViera'}, {'key': 'snapchat', 'label': 'Snapchat'},
                      {'key': 'snowtape', 'label': 'Snowtape'},
                      {'key': 'sogou_explorer', 'label': 'Sogou Explorer'},
                      {'key': 'sogou_mobile', 'label': 'Sogou Mobile'},
                      {'key': 'sohunews_app', 'label': 'SohuNews App'},
                      {'key': 'songbird_app', 'label': 'Songbird App'}, {'key': 'sony', 'label': 'Sony'},
                      {'key': 'sony_ps2', 'label': 'Sony PS2'}, {'key': 'sony_psp', 'label': 'Sony PSP'},
                      {'key': 'soundcloud_app', 'label': 'SoundCloud App'},
                      {'key': 'sparrow', 'label': 'Sparrow'}, {'key': 'spector', 'label': 'Spector'},
                      {'key': 'sports_talk_1050', 'label': 'Sports Talk 1050'},
                      {'key': 'spotify', 'label': 'Spotify'},
                      {'key': 'sputnik_browser', 'label': 'Sputnik Browser'},
                      {'key': 'sraf', 'label': 'Sraf'}, {'key': 'stainless', 'label': 'Stainless'},
                      {'key': 'start_browser', 'label': 'Start Browser'}, {'key': 'steam', 'label': 'Steam'},
                      {'key': 'steam_big_picture', 'label': 'Steam Big Picture'},
                      {'key': 'steam_overlay', 'label': 'Steam Overlay'},
                      {'key': 'stitcher', 'label': 'Stitcher'},
                      {'key': 'streaming_player', 'label': 'Streaming Player'},
                      {'key': 'sundance', 'label': 'Sundance'}, {'key': 'sunrise', 'label': 'Sunrise'},
                      {'key': 'superbird', 'label': 'SuperBird'},
                      {'key': 'surf_browser', 'label': 'Surf Browser'}, {'key': 'swing', 'label': 'Swing'},
                      {'key': 'symphony_browser', 'label': 'Symphony Browser'},
                      {'key': 'twc_sportsnet', 'label': 'TWC SportsNet'},
                      {'key': 'tazweb', 'label': 'TazWeb'}, {'key': 'teleca-obigo', 'label': 'Teleca-Obigo'},
                      {'key': 'tenfourfox', 'label': 'TenFourFox'},
                      {'key': 'tenta_browser', 'label': 'Tenta Browser'}, {'key': 'terra', 'label': 'Terra'},
                      {'key': 'teslabrowser', 'label': 'TeslaBrowser'}, {'key': 'tevion', 'label': 'Tevion'},
                      {'key': 'the_bat!', 'label': 'The Bat!'},
                      {'key': 'the_dan_patrick_show', 'label': 'The Dan Patrick Show'},
                      {'key': 'the_diary', 'label': 'The Diary'}, {'key': 'theworld', 'label': 'TheWorld'},
                      {'key': 'thunderbird', 'label': 'Thunderbird'},
                      {'key': 'tinybrowser', 'label': 'TinyBrowser'},
                      {'key': 'tizen_browser', 'label': 'Tizen Browser'},
                      {'key': 'toppodcasts', 'label': 'TopPodcasts'}, {'key': 'tubetv', 'label': 'TubeTV'},
                      {'key': 'tungsten_browser', 'label': 'Tungsten Browser'},
                      {'key': 'tweetbot', 'label': 'Tweetbot'},
                      {'key': 'twitter_app', 'label': 'Twitter App'},
                      {'key': 'uc_browser', 'label': 'UC Browser'},
                      {'key': 'uc_browser_hd', 'label': 'UC Browser HD'},
                      {'key': 'uc_browser_mini', 'label': 'UC Browser Mini'},
                      {'key': 'ur_browser', 'label': 'UR Browser'},
                      {'key': 'vlc_media_player', 'label': 'VLC Media Player'},
                      {'key': 'vms_mosaic', 'label': 'VMS_Mosaic'},
                      {'key': 'vox_music_player', 'label': 'VOX Music Player'},
                      {'key': 'vanillasurf', 'label': 'VanillaSurf'}, {'key': 'vienna', 'label': 'Vienna'},
                      {'key': 'visio', 'label': 'Visio'}, {'key': 'vitelcom', 'label': 'Vitelcom'},
                      {'key': 'vivaldi', 'label': 'Vivaldi'},
                      {'key': 'vmware_browser', 'label': 'VmWare Browser'},
                      {'key': 'vodafone', 'label': 'Vodafone'}, {'key': 'vonkeror', 'label': 'Vonkeror'},
                      {'key': 'voyager', 'label': 'Voyager'}, {'key': 'wap_browser', 'label': 'WAP Browser'},
                      {'key': 'wkbrowser', 'label': 'WKBrowser'},
                      {'key': 'wahoo_browser', 'label': 'Wahoo Browser'},
                      {'key': 'waterfox', 'label': 'Waterfox'}, {'key': 'wechat_app', 'label': 'WeChat App'},
                      {'key': 'wetab_browser', 'label': 'WeTab Browser'},
                      {'key': 'webclip_app', 'label': 'WebClip App'},
                      {'key': 'webkit/webos', 'label': 'WebKit/webOS'},
                      {'key': 'webpirate_browser', 'label': 'WebPirate Browser'},
                      {'key': 'webtv/msntv', 'label': 'WebTV/MSNTV'},
                      {'key': 'webthumb', 'label': 'WebThumb'}, {'key': 'weibo', 'label': 'Weibo'},
                      {'key': 'whale_browser', 'label': 'Whale Browser'},
                      {'key': 'whatsapp', 'label': 'WhatsApp'},
                      {'key': 'whitehat_aviator', 'label': 'WhiteHat Aviator'},
                      {'key': 'winamp', 'label': 'WinAmp'}, {'key': 'winwap', 'label': 'WinWAP'},
                      {'key': 'windows_live_mail', 'label': 'Windows Live Mail'},
                      {'key': 'windows_media_player', 'label': 'Windows Media Player'},
                      {'key': 'windows_powershell', 'label': 'Windows PowerShell'},
                      {'key': 'windows-update-agent', 'label': 'Windows-Update-Agent'},
                      {'key': 'wire_app', 'label': 'Wire App'}, {'key': 'word', 'label': 'Word'},
                      {'key': 'wordpress_app', 'label': 'WordPress App'}, {'key': 'wyzo', 'label': 'Wyzo'},
                      {'key': 'yolo_browser', 'label': 'YOLO Browser'}, {'key': 'yaapp', 'label': 'YaApp'},
                      {'key': 'yahoo_mail_mobile', 'label': 'Yahoo Mail Mobile'},
                      {'key': 'yahoo_messenger', 'label': 'Yahoo Messenger'},
                      {'key': 'yahoo_mobile_app', 'label': 'Yahoo Mobile App'},
                      {'key': 'yahoo!_app', 'label': 'Yahoo! App'},
                      {'key': 'yandex_browser', 'label': 'Yandex Browser'},
                      {'key': 'yandex_search', 'label': 'Yandex Search'},
                      {'key': 'yellowpages_mobile_app', 'label': 'YellowPages Mobile App'},
                      {'key': 'youwave_android_on_pc', 'label': 'YouWave Android on PC'},
                      {'key': 'zte', 'label': 'ZTE'}, {'key': 'zetakey_browser', 'label': 'Zetakey Browser'},
                      {'key': 'zimbra_desktop', 'label': 'Zimbra Desktop'}, {'key': 'zune', 'label': 'Zune'},
                      {'key': 'zvu', 'label': 'Zvu'}, {'key': 'akregator', 'label': 'akregator'},
                      {'key': 'bpod', 'label': 'bPod'},
                      {'key': 'billigfluegefinal_app', 'label': 'billigFluegeFinal App'},
                      {'key': 'bumblebee', 'label': 'bumblebee'}, {'key': 'ccwap', 'label': 'ccWAP'},
                      {'key': 'douban_app', 'label': 'douban App'}, {'key': 'fantomas', 'label': 'fantomas'},
                      {'key': 'fantomas_cloakbrowser', 'label': 'fantomas cloakBrowser'},
                      {'key': 'fantomas_fantombrowser', 'label': 'fantomas fantomBrowser'},
                      {'key': 'fantomas_fantomcrew_browser', 'label': 'fantomas fantomCrew Browser'},
                      {'key': 'fantomas_multiblocker_browser', 'label': 'fantomas multiBlocker browser'},
                      {'key': 'fantomas_shadowmaker_browser', 'label': 'fantomas shadowMaker Browser'},
                      {'key': 'fantomas_stealthbrowser', 'label': 'fantomas stealthBrowser'},
                      {'key': 'fgbrowser', 'label': 'fgBrowser'},
                      {'key': 'foobar2000', 'label': 'foobar2000'}, {'key': 'gpodder', 'label': 'gPodder'},
                      {'key': 'i-mobile', 'label': 'i-mobile'},
                      {'key': 'i-mode_browser', 'label': 'i-mode Browser'},
                      {'key': 'iball', 'label': 'iBall'}, {'key': 'ibooks_author', 'label': 'iBooks Author'},
                      {'key': 'ibrowser', 'label': 'iBrowser'}, {'key': 'icab', 'label': 'iCab'},
                      {'key': 'icab_mobile', 'label': 'iCab Mobile'},
                      {'key': 'ilunascape', 'label': 'iLunascape'},
                      {'key': 'ios_dataaccessd', 'label': 'iOS dataaccessd'},
                      {'key': 'iphone_simulator', 'label': 'iPhone Simulator'},
                      {'key': 'ipick', 'label': 'iPick'}, {'key': 'ipodder', 'label': 'iPodder'},
                      {'key': 'isearch', 'label': 'iSearch'}, {'key': 'isilox', 'label': 'iSiloX'},
                      {'key': 'itunes', 'label': 'iTunes'}, {'key': 'iweb', 'label': 'iWeb'},
                      {'key': 'jbrowser', 'label': 'jBrowser'}, {'key': 'jpodder', 'label': 'jPodder'},
                      {'key': 'jig_browser_web', 'label': 'jig browser web'},
                      {'key': 'kejian', 'label': 'kejian'}, {'key': 'kioclient', 'label': 'kioclient'},
                      {'key': 'lftp', 'label': 'lftp'}, {'key': 'liebao', 'label': 'liebao'},
                      {'key': 'lolifox', 'label': 'lolifox'}, {'key': 'luakit', 'label': 'luakit'},
                      {'key': 'noadsbrowser', 'label': 'noadsbrowser'},
                      {'key': 'open-webkit-sharp', 'label': 'open-webkit-sharp'},
                      {'key': 'phantomas', 'label': 'phantomas'},
                      {'key': 'philpodder', 'label': 'philpodder'}, {'key': 'podracer', 'label': 'podracer'},
                      {'key': 'qutebrowser', 'label': 'qutebrowser'}, {'key': 'rekonq', 'label': 'rekonq'},
                      {'key': 'stagefright', 'label': 'stagefright'}, {'key': 'vobsub', 'label': 'vobsub'},
                      {'key': 'w3m', 'label': 'w3m'}, {'key': 'wkhtmltoimage', 'label': 'wkhtmltoimage'},
                      {'key': 'wkhtmltopdf', 'label': 'wkhtmltopdf'}]}
            ]
