def get_values():
    return [{"label": "Country",
             "key": "country",
             "type": "dict",
             "data": [{"key": "AF", "label": "Afghanistan"}, {"key": "AX", "label": "\u00c5land Islands"},
                      {"key": "AL", "label": "Albania"}, {"key": "DZ", "label": "Algeria"},
                      {"key": "AS", "label": "American Samoa"}, {"key": "AD", "label": "Andorra"},
                      {"key": "AO", "label": "Angola"}, {"key": "AI", "label": "Anguilla"},
                      {"key": "AQ", "label": "Antarctica"}, {"key": "AG", "label": "Antigua and Barbuda"},
                      {"key": "AR", "label": "Argentina"}, {"key": "AM", "label": "Armenia"},
                      {"key": "AW", "label": "Aruba"}, {"key": "AU", "label": "Australia"},
                      {"key": "AT", "label": "Austria"}, {"key": "AZ", "label": "Azerbaijan"},
                      {"key": "BS", "label": "Bahamas"}, {"key": "BH", "label": "Bahrain"},
                      {"key": "BD", "label": "Bangladesh"}, {"key": "BB", "label": "Barbados"},
                      {"key": "BY", "label": "Belarus"}, {"key": "BE", "label": "Belgium"},
                      {"key": "BZ", "label": "Belize"}, {"key": "BJ", "label": "Benin"},
                      {"key": "BM", "label": "Bermuda"}, {"key": "BT", "label": "Bhutan"},
                      {"key": "BO", "label": "Bolivia, Plurinational State of"},
                      {"key": "BQ", "label": "Bonaire, Sint Eustatius and Saba"},
                      {"key": "BA", "label": "Bosnia and Herzegovina"}, {"key": "BW", "label": "Botswana"},
                      {"key": "BV", "label": "Bouvet Island"}, {"key": "BR", "label": "Brazil"},
                      {"key": "IO", "label": "British Indian Ocean Territory"},
                      {"key": "BN", "label": "Brunei Darussalam"}, {"key": "BG", "label": "Bulgaria"},
                      {"key": "BF", "label": "Burkina Faso"}, {"key": "BI", "label": "Burundi"},
                      {"key": "KH", "label": "Cambodia"}, {"key": "CM", "label": "Cameroon"},
                      {"key": "CA", "label": "Canada"}, {"key": "CV", "label": "Cape Verde"},
                      {"key": "KY", "label": "Cayman Islands"}, {"key": "CF", "label": "Central African Republic"},
                      {"key": "TD", "label": "Chad"}, {"key": "CL", "label": "Chile"},
                      {"key": "CN", "label": "China"}, {"key": "CX", "label": "Christmas Island"},
                      {"key": "CC", "label": "Cocos (Keeling) Islands"}, {"key": "CO", "label": "Colombia"},
                      {"key": "KM", "label": "Comoros"}, {"key": "CG", "label": "Congo"},
                      {"key": "CD", "label": "Congo, the Democratic Republic of the"},
                      {"key": "CK", "label": "Cook Islands"}, {"key": "CR", "label": "Costa Rica"},
                      {"key": "CI", "label": "C\u00f4te d'Ivoire"}, {"key": "HR", "label": "Croatia"},
                      {"key": "CU", "label": "Cuba"}, {"key": "CW", "label": "Cura\u00e7ao"},
                      {"key": "CY", "label": "Cyprus"}, {"key": "CZ", "label": "Czech Republic"},
                      {"key": "DK", "label": "Denmark"}, {"key": "DJ", "label": "Djibouti"},
                      {"key": "DM", "label": "Dominica"}, {"key": "DO", "label": "Dominican Republic"},
                      {"key": "EC", "label": "Ecuador"}, {"key": "EG", "label": "Egypt"},
                      {"key": "SV", "label": "El Salvador"}, {"key": "GQ", "label": "Equatorial Guinea"},
                      {"key": "ER", "label": "Eritrea"}, {"key": "EE", "label": "Estonia"},
                      {"key": "ET", "label": "Ethiopia"}, {"key": "FK", "label": "Falkland Islands (Malvinas)"},
                      {"key": "FO", "label": "Faroe Islands"}, {"key": "FJ", "label": "Fiji"},
                      {"key": "FI", "label": "Finland"}, {"key": "FR", "label": "France"},
                      {"key": "GF", "label": "French Guiana"}, {"key": "PF", "label": "French Polynesia"},
                      {"key": "TF", "label": "French Southern Territories"}, {"key": "GA", "label": "Gabon"},
                      {"key": "GM", "label": "Gambia"}, {"key": "GE", "label": "Georgia"},
                      {"key": "DE", "label": "Germany"}, {"key": "GH", "label": "Ghana"},
                      {"key": "GI", "label": "Gibraltar"}, {"key": "GR", "label": "Greece"},
                      {"key": "GL", "label": "Greenland"}, {"key": "GD", "label": "Grenada"},
                      {"key": "GP", "label": "Guadeloupe"}, {"key": "GU", "label": "Guam"},
                      {"key": "GT", "label": "Guatemala"}, {"key": "GG", "label": "Guernsey"},
                      {"key": "GN", "label": "Guinea"}, {"key": "GW", "label": "Guinea-Bissau"},
                      {"key": "GY", "label": "Guyana"}, {"key": "HT", "label": "Haiti"},
                      {"key": "HM", "label": "Heard Island and McDonald Islands"},
                      {"key": "VA", "label": "Holy See (Vatican City State)"}, {"key": "HN", "label": "Honduras"},
                      {"key": "HK", "label": "Hong Kong"}, {"key": "HU", "label": "Hungary"},
                      {"key": "IS", "label": "Iceland"}, {"key": "IN", "label": "India"},
                      {"key": "ID", "label": "Indonesia"}, {"key": "IR", "label": "Iran, Islamic Republic of"},
                      {"key": "IQ", "label": "Iraq"}, {"key": "IE", "label": "Ireland"},
                      {"key": "IM", "label": "Isle of Man"}, {"key": "IL", "label": "Israel"},
                      {"key": "IT", "label": "Italy"}, {"key": "JM", "label": "Jamaica"},
                      {"key": "JP", "label": "Japan"}, {"key": "JE", "label": "Jersey"},
                      {"key": "JO", "label": "Jordan"}, {"key": "KZ", "label": "Kazakhstan"},
                      {"key": "KE", "label": "Kenya"}, {"key": "KI", "label": "Kiribati"},
                      {"key": "KP", "label": "Korea, Democratic People's Republic of"},
                      {"key": "KR", "label": "Korea, Republic of"}, {"key": "KW", "label": "Kuwait"},
                      {"key": "KG", "label": "Kyrgyzstan"},
                      {"key": "LA", "label": "Lao People's Democratic Republic"}, {"key": "LV", "label": "Latvia"},
                      {"key": "LB", "label": "Lebanon"}, {"key": "LS", "label": "Lesotho"},
                      {"key": "LR", "label": "Liberia"}, {"key": "LY", "label": "Libya"},
                      {"key": "LI", "label": "Liechtenstein"}, {"key": "LT", "label": "Lithuania"},
                      {"key": "LU", "label": "Luxembourg"}, {"key": "MO", "label": "Macao"},
                      {"key": "MK", "label": "Macedonia, the Former Yugoslav Republic of"},
                      {"key": "MG", "label": "Madagascar"}, {"key": "MW", "label": "Malawi"},
                      {"key": "MY", "label": "Malaysia"}, {"key": "MV", "label": "Maldives"},
                      {"key": "ML", "label": "Mali"}, {"key": "MT", "label": "Malta"},
                      {"key": "MH", "label": "Marshall Islands"}, {"key": "MQ", "label": "Martinique"},
                      {"key": "MR", "label": "Mauritania"}, {"key": "MU", "label": "Mauritius"},
                      {"key": "YT", "label": "Mayotte"}, {"key": "MX", "label": "Mexico"},
                      {"key": "FM", "label": "Micronesia, Federated States of"},
                      {"key": "MD", "label": "Moldova, Republic of"}, {"key": "MC", "label": "Monaco"},
                      {"key": "MN", "label": "Mongolia"}, {"key": "ME", "label": "Montenegro"},
                      {"key": "MS", "label": "Montserrat"}, {"key": "MA", "label": "Morocco"},
                      {"key": "MZ", "label": "Mozambique"}, {"key": "MM", "label": "Myanmar"},
                      {"key": "NA", "label": "Namibia"}, {"key": "NR", "label": "Nauru"},
                      {"key": "NP", "label": "Nepal"}, {"key": "NL", "label": "Netherlands"},
                      {"key": "NC", "label": "New Caledonia"}, {"key": "NZ", "label": "New Zealand"},
                      {"key": "NI", "label": "Nicaragua"}, {"key": "NE", "label": "Niger"},
                      {"key": "NG", "label": "Nigeria"}, {"key": "NU", "label": "Niue"},
                      {"key": "NF", "label": "Norfolk Island"}, {"key": "MP", "label": "Northern Mariana Islands"},
                      {"key": "NO", "label": "Norway"}, {"key": "OM", "label": "Oman"},
                      {"key": "PK", "label": "Pakistan"}, {"key": "PW", "label": "Palau"},
                      {"key": "PS", "label": "Palestine, State of"}, {"key": "PA", "label": "Panama"},
                      {"key": "PG", "label": "Papua New Guinea"}, {"key": "PY", "label": "Paraguay"},
                      {"key": "PE", "label": "Peru"}, {"key": "PH", "label": "Philippines"},
                      {"key": "PN", "label": "Pitcairn"}, {"key": "PL", "label": "Poland"},
                      {"key": "PT", "label": "Portugal"}, {"key": "PR", "label": "Puerto Rico"},
                      {"key": "QA", "label": "Qatar"}, {"key": "RE", "label": "R\u00e9union"},
                      {"key": "RO", "label": "Romania"}, {"key": "RU", "label": "Russian Federation"},
                      {"key": "RW", "label": "Rwanda"}, {"key": "BL", "label": "Saint Barth\u00e9lemy"},
                      {"key": "SH", "label": "Saint Helena, Ascension and Tristan da Cunha"},
                      {"key": "KN", "label": "Saint Kitts and Nevis"}, {"key": "LC", "label": "Saint Lucia"},
                      {"key": "MF", "label": "Saint Martin (French part)"},
                      {"key": "PM", "label": "Saint Pierre and Miquelon"},
                      {"key": "VC", "label": "Saint Vincent and the Grenadines"}, {"key": "WS", "label": "Samoa"},
                      {"key": "SM", "label": "San Marino"}, {"key": "ST", "label": "Sao Tome and Principe"},
                      {"key": "SA", "label": "Saudi Arabia"}, {"key": "SN", "label": "Senegal"},
                      {"key": "RS", "label": "Serbia"}, {"key": "SC", "label": "Seychelles"},
                      {"key": "SL", "label": "Sierra Leone"}, {"key": "SG", "label": "Singapore"},
                      {"key": "SX", "label": "Sint Maarten (Dutch part)"}, {"key": "SK", "label": "Slovakia"},
                      {"key": "SI", "label": "Slovenia"}, {"key": "SB", "label": "Solomon Islands"},
                      {"key": "SO", "label": "Somalia"}, {"key": "ZA", "label": "South Africa"},
                      {"key": "GS", "label": "South Georgia and the South Sandwich Islands"},
                      {"key": "SS", "label": "South Sudan"}, {"key": "ES", "label": "Spain"},
                      {"key": "LK", "label": "Sri Lanka"}, {"key": "SD", "label": "Sudan"},
                      {"key": "SR", "label": "Surilabel"}, {"key": "SJ", "label": "Svalbard and Jan Mayen"},
                      {"key": "SZ", "label": "Swaziland"}, {"key": "SE", "label": "Sweden"},
                      {"key": "CH", "label": "Switzerland"}, {"key": "SY", "label": "Syrian Arab Republic"},
                      {"key": "TW", "label": "Taiwan, Province of China"}, {"key": "TJ", "label": "Tajikistan"},
                      {"key": "TZ", "label": "Tanzania, United Republic of"}, {"key": "TH", "label": "Thailand"},
                      {"key": "TL", "label": "Timor-Leste"}, {"key": "TG", "label": "Togo"},
                      {"key": "TK", "label": "Tokelau"}, {"key": "TO", "label": "Tonga"},
                      {"key": "TT", "label": "Trinidad and Tobago"}, {"key": "TN", "label": "Tunisia"},
                      {"key": "TR", "label": "Turkey"}, {"key": "TM", "label": "Turkmenistan"},
                      {"key": "TC", "label": "Turks and Caicos Islands"}, {"key": "TV", "label": "Tuvalu"},
                      {"key": "UG", "label": "Uganda"}, {"key": "UA", "label": "Ukraine"},
                      {"key": "AE", "label": "United Arab Emirates"}, {"key": "GB", "label": "United Kingdom"},
                      {"key": "US", "label": "United States"},
                      {"key": "UM", "label": "United States Minor Outlying Islands"},
                      {"key": "UY", "label": "Uruguay"}, {"key": "UZ", "label": "Uzbekistan"},
                      {"key": "VU", "label": "Vanuatu"},
                      {"key": "VE", "label": "Venezuela, Bolivarian Republic of"},
                      {"key": "VN", "label": "Viet Nam"}, {"key": "VG", "label": "Virgin Islands, British"},
                      {"key": "VI", "label": "Virgin Islands, U.S."}, {"key": "WF", "label": "Wallis and Futuna"},
                      {"key": "EH", "label": "Western Sahara"}, {"key": "YE", "label": "Yemen"},
                      {"key": "ZM", "label": "Zambia"}, {"key": "ZW", "label": "Zimbabwe"}]
             },
            {"label": "Device type", "key": "deviceType",
             "type": "dict",
             "data": [{"key": "carEntertainmentSystem", "label": "Car Entertainment System"},
                      {"key": "console", "label": "Console"}, {"key": "desktop", "label": "Desktop"},
                      {"key": "digitalCamera", "label": "Digital Camera"},
                      {"key": "ebookReader", "label": "Ebook Reader"},
                      {"key": "mobileDevice", "label": "Mobile Device"},
                      {"key": "mobilePhone", "label": "Mobile Phone"},
                      {"key": "tvDevice", "label": "TV Device"}, {"key": "tablet", "label": "Tablet"}]},
            {"label": "JavaScript", "key": "javascript",
             "type": "bool"},
            {"label": "Operating System", "key": "platform",
             "type": "dict",
             "data": [{"key": "aix", "label": "AIX"}, {"key": "atvOsX", "label": "ATV OS X"},
                      {"key": "amigaOs", "label": "Amiga OS"}, {"key": "android", "label": "Android"},
                      {"key": "androidForGoogletv", "label": "Android for GoogleTV"},
                      {"key": "asha", "label": "Asha"}, {"key": "bsd", "label": "BSD"},
                      {"key": "bada", "label": "Bada"}, {"key": "beos", "label": "BeOS"},
                      {"key": "brew", "label": "Brew"}, {"key": "brewMp", "label": "Brew MP"},
                      {"key": "cellos", "label": "CellOS"}, {"key": "centos", "label": "CentOS"},
                      {"key": "chromeos", "label": "ChromeOS"},
                      {"key": "chromecastOs", "label": "Chromecast OS"},
                      {"key": "cygwin", "label": "CygWin"}, {"key": "darwin", "label": "Darwin"},
                      {"key": "debian", "label": "Debian"},
                      {"key": "dragonflyBsd", "label": "DragonFly BSD"},
                      {"key": "fedora", "label": "Fedora"}, {"key": "firefoxos", "label": "FirefoxOS"},
                      {"key": "freebsd", "label": "FreeBSD"}, {"key": "hp-ux", "label": "HP-UX"},
                      {"key": "haiku", "label": "Haiku"}, {"key": "irix64", "label": "IRIX64"},
                      {"key": "infernoOs", "label": "Inferno OS"}, {"key": "java", "label": "JAVA"},
                      {"key": "kaios", "label": "KaiOS"}, {"key": "linux", "label": "Linux"},
                      {"key": "maui", "label": "MAUI"}, {"key": "mac68k", "label": "Mac68K"},
                      {"key": "macosx", "label": "MacOSX"}, {"key": "macppc", "label": "MacPPC"},
                      {"key": "maemo", "label": "Maemo"}, {"key": "meego", "label": "MeeGo"},
                      {"key": "miuiOs", "label": "Miui OS"}, {"key": "mobilinux", "label": "Mobilinux"},
                      {"key": "netbsd", "label": "NetBSD"},
                      {"key": "nintendo3ds", "label": "Nintendo 3DS"},
                      {"key": "nintendoDs", "label": "Nintendo DS"},
                      {"key": "nintendoDsi", "label": "Nintendo DSi"},
                      {"key": "nintendoSwitch", "label": "Nintendo Switch"},
                      {"key": "nintendoWii", "label": "Nintendo Wii"},
                      {"key": "nintendoWiiu", "label": "Nintendo WiiU"}, {"key": "os/2", "label": "OS/2"},
                      {"key": "openbsd", "label": "OpenBSD"}, {"key": "openvms", "label": "OpenVMS"},
                      {"key": "orbisos", "label": "OrbisOS"}, {"key": "palmos", "label": "PalmOS"},
                      {"key": "playstationVita", "label": "Playstation Vita"},
                      {"key": "rimOs", "label": "RIM OS"},
                      {"key": "rimTabletOs", "label": "RIM Tablet OS"},
                      {"key": "riscOs", "label": "RISC OS"}, {"key": "redHat", "label": "Red Hat"},
                      {"key": "sailfishos", "label": "SailfishOS"},
                      {"key": "series30", "label": "Series30"}, {"key": "series40", "label": "Series40"},
                      {"key": "solaris", "label": "Solaris"}, {"key": "sunos", "label": "SunOS"},
                      {"key": "syllable", "label": "Syllable"}, {"key": "symbianos", "label": "SymbianOS"},
                      {"key": "tizen", "label": "Tizen"}, {"key": "tru64Unix", "label": "Tru64 UNIX"},
                      {"key": "ubuntu", "label": "Ubuntu"},
                      {"key": "ubuntuTouch", "label": "Ubuntu Touch"}, {"key": "unix", "label": "Unix"},
                      {"key": "win10", "label": "Win10"}, {"key": "win16", "label": "Win16"},
                      {"key": "win2000", "label": "Win2000"}, {"key": "win31", "label": "Win31"},
                      {"key": "win32", "label": "Win32"}, {"key": "win64", "label": "Win64"},
                      {"key": "win7", "label": "Win7"}, {"key": "win8", "label": "Win8"},
                      {"key": "win8.1", "label": "Win8.1"}, {"key": "win95", "label": "Win95"},
                      {"key": "win98", "label": "Win98"}, {"key": "wince", "label": "WinCE"},
                      {"key": "winme", "label": "WinME"}, {"key": "winmobile", "label": "WinMobile"},
                      {"key": "winnt", "label": "WinNT"}, {"key": "winphone", "label": "WinPhone"},
                      {"key": "winphone10", "label": "WinPhone10"},
                      {"key": "winphone6", "label": "WinPhone6"},
                      {"key": "winphone7", "label": "WinPhone7"},
                      {"key": "winphone7.5", "label": "WinPhone7.5"},
                      {"key": "winphone7.8", "label": "WinPhone7.8"},
                      {"key": "winphone8", "label": "WinPhone8"},
                      {"key": "winphone8.1", "label": "WinPhone8.1"}, {"key": "winrt8", "label": "WinRT8"},
                      {"key": "winrt8.1", "label": "WinRT8.1"}, {"key": "winvista", "label": "WinVista"},
                      {"key": "winxp", "label": "WinXP"}, {"key": "xbox360", "label": "Xbox 360"},
                      {"key": "xbox360(mobileView)", "label": "Xbox 360 (Mobile View)"},
                      {"key": "xboxOs", "label": "Xbox OS"},
                      {"key": "xboxOs(mobileView)", "label": "Xbox OS (Mobile View)"},
                      {"key": "xboxOs10", "label": "Xbox OS 10"},
                      {"key": "xboxOs10(mobileView)", "label": "Xbox OS 10 (Mobile View)"},
                      {"key": "ios", "label": "iOS"}, {"key": "macos", "label": "macOS"},
                      {"key": "webos", "label": "webOS"}]},
            {"label": "Browser", "key": "browser",
             "type": "dict",
             "data": [{"key": "115Browser", "label": "115 Browser"},
                      {"key": "1password", "label": "1Password"},
                      {"key": "1passwordthumbs", "label": "1PasswordThumbs"},
                      {"key": "1stbrowser", "label": "1stBrowser"},
                      {"key": "2345Browser", "label": "2345 Browser"},
                      {"key": "2345Chrome", "label": "2345 Chrome"},
                      {"key": "2345Explorer", "label": "2345 Explorer"},
                      {"key": "360SecureBrowser", "label": "360 Secure Browser"},
                      {"key": "360SpeedBrowser", "label": "360 Speed Browser"},
                      {"key": "37abc", "label": "37abc"}, {"key": "7Star", "label": "7 Star"},
                      {"key": "77Wabc", "label": "77 WABC"}, {"key": "abrowse", "label": "ABrowse"},
                      {"key": "antGalio", "label": "ANT Galio"}, {"key": "aolApp", "label": "AOL App"},
                      {"key": "aolDesktop", "label": "AOL Desktop"},
                      {"key": "aolShield", "label": "AOL Shield"},
                      {"key": "apusbrowser", "label": "APUSBrowser"}, {"key": "attws", "label": "ATTWS"},
                      {"key": "au", "label": "AU"}, {"key": "access", "label": "Access"},
                      {"key": "acooBrowser", "label": "Acoo Browser"},
                      {"key": "adobeAir", "label": "Adobe AIR"}, {"key": "airmail", "label": "Airmail"},
                      {"key": "alcatel", "label": "Alcatel"},
                      {"key": "alexaMediaplayer", "label": "Alexa MediaPlayer"},
                      {"key": "aliapp", "label": "AliApp"}, {"key": "alienforce", "label": "Alienforce"},
                      {"key": "alltopApp", "label": "Alltop App"},
                      {"key": "alohaBrowser", "label": "Aloha Browser"},
                      {"key": "amarok", "label": "Amarok"}, {"key": "amaya", "label": "Amaya"},
                      {"key": "amigo", "label": "Amigo"}, {"key": "amoi", "label": "Amoi"},
                      {"key": "android", "label": "Android"},
                      {"key": "androidDownloadManager", "label": "Android Download Manager"},
                      {"key": "androidWebview", "label": "Android WebView"},
                      {"key": "antennapod", "label": "AntennaPod"},
                      {"key": "appleAppstoreApp", "label": "Apple AppStore App"},
                      {"key": "appleMail", "label": "Apple Mail"},
                      {"key": "appleNews", "label": "Apple News"},
                      {"key": "applePubsub", "label": "Apple PubSub"},
                      {"key": "applecoremedia", "label": "AppleCoreMedia"},
                      {"key": "argclrint", "label": "ArgClrInt"}, {"key": "arora", "label": "Arora"},
                      {"key": "asus", "label": "Asus"}, {"key": "atomicBrowser", "label": "Atomic Browser"},
                      {"key": "audioboom", "label": "AudioBoom"}, {"key": "automator", "label": "Automator"},
                      {"key": "avant", "label": "Avant"},
                      {"key": "avastSafezone", "label": "Avast SafeZone"},
                      {"key": "aviraScout", "label": "Avira Scout"}, {"key": "b-line", "label": "B-Line"},
                      {"key": "bb2c", "label": "BB2C"}, {"key": "bird", "label": "BIRD"},
                      {"key": "baiduBoxApp", "label": "Baidu Box App"},
                      {"key": "baiduBrowser", "label": "Baidu Browser"},
                      {"key": "baiduBrowserHd", "label": "Baidu Browser HD"},
                      {"key": "baiduBrowserMini", "label": "Baidu Browser Mini"},
                      {"key": "bansheeMediaPlayer", "label": "Banshee Media Player"},
                      {"key": "barcaMailClient", "label": "Barca Mail Client"},
                      {"key": "bashpodder", "label": "BashPodder"},
                      {"key": "battle.netOverlay", "label": "Battle.net Overlay"},
                      {"key": "beamrise", "label": "Beamrise"}, {"key": "bellwave", "label": "Bellwave"},
                      {"key": "benq", "label": "BenQ"},
                      {"key": "beonexCommunicator", "label": "Beonex Communicator"},
                      {"key": "beyondpod", "label": "BeyondPod"},
                      {"key": "bigslickgofish", "label": "BigSlickGoFish"}, {"key": "bing", "label": "Bing"},
                      {"key": "bingSearchApp", "label": "Bing Search App"},
                      {"key": "bingIpad", "label": "Bing iPad"},
                      {"key": "blackberry", "label": "BlackBerry"},
                      {"key": "blackberryPlaybookTablet", "label": "Blackberry Playbook Tablet"},
                      {"key": "blackhawk", "label": "Blackhawk"}, {"key": "blazer", "label": "Blazer"},
                      {"key": "blueBrowser", "label": "Blue Browser"}, {"key": "bolt", "label": "Bolt"},
                      {"key": "bowser", "label": "Bowser"}, {"key": "boxee", "label": "Boxee"},
                      {"key": "brave", "label": "Brave"}, {"key": "browzar", "label": "Browzar"},
                      {"key": "cfnetwork", "label": "CFNetwork"},
                      {"key": "cmBrowser", "label": "CM Browser"},
                      {"key": "cmuvDvbviewer", "label": "CMUV DVBViewer"}, {"key": "ctl", "label": "CTL"},
                      {"key": "camera360", "label": "Camera 360"}, {"key": "camino", "label": "Camino"},
                      {"key": "centBrowser", "label": "Cent Browser"}, {"key": "charon", "label": "Charon"},
                      {"key": "chedot", "label": "Chedot"}, {"key": "cheshire", "label": "Cheshire"},
                      {"key": "chimera", "label": "Chimera"}, {"key": "chrome", "label": "Chrome"},
                      {"key": "chromeplus", "label": "ChromePlus"}, {"key": "chromium", "label": "Chromium"},
                      {"key": "classilla", "label": "Classilla"},
                      {"key": "clementine", "label": "Clementine"}, {"key": "clipish", "label": "Clipish"},
                      {"key": "coast", "label": "Coast"},
                      {"key": "cocCocBrowser", "label": "Coc Coc Browser"},
                      {"key": "coda", "label": "Coda"}, {"key": "cometbird", "label": "CometBird"},
                      {"key": "conkeror", "label": "Conkeror"}, {"key": "coolnovo", "label": "CoolNovo"},
                      {"key": "cooliris", "label": "Cooliris"},
                      {"key": "courseraMobileApp", "label": "Coursera Mobile App"},
                      {"key": "coverscout", "label": "CoverScout"},
                      {"key": "crazyBrowser", "label": "Crazy Browser"},
                      {"key": "crosswalkApp", "label": "Crosswalk App"},
                      {"key": "crowsnestMobileApp", "label": "Crowsnest Mobile App"},
                      {"key": "cunaguaro", "label": "Cunaguaro"}, {"key": "custom", "label": "Custom"},
                      {"key": "cybeye", "label": "CybEye"}, {"key": "cyberdog", "label": "Cyberdog"},
                      {"key": "cyberduck", "label": "Cyberduck"}, {"key": "cyberfox", "label": "Cyberfox"},
                      {"key": "dbtel", "label": "DBTEL"}, {"key": "dalvik", "label": "Dalvik"},
                      {"key": "darwinBrowser", "label": "Darwin Browser"}, {"key": "daum", "label": "Daum"},
                      {"key": "davidClient", "label": "David Client"},
                      {"key": "deepnetExplorer", "label": "Deepnet Explorer"},
                      {"key": "defaultBrowser", "label": "Default Browser"},
                      {"key": "defaultproperties", "label": "DefaultProperties"},
                      {"key": "diglo", "label": "Diglo"}, {"key": "diigoBrowser", "label": "Diigo Browser"},
                      {"key": "dillo", "label": "Dillo"}, {"key": "docomo", "label": "DoCoMo"},
                      {"key": "doggcatcher", "label": "DoggCatcher"}, {"key": "dolfin", "label": "Dolfin"},
                      {"key": "doppler", "label": "Doppler"},
                      {"key": "doradoWapBrowser", "label": "Dorado WAP Browser"},
                      {"key": "doris", "label": "Doris"}, {"key": "downcast", "label": "Downcast"},
                      {"key": "dragon", "label": "Dragon"}, {"key": "dreamweaver", "label": "Dreamweaver"},
                      {"key": "duckduckApp", "label": "DuckDuck App"},
                      {"key": "ebIphone/ipadApp", "label": "EB iPhone/IPad App"},
                      {"key": "elinks", "label": "ELinks"}, {"key": "esatcom", "label": "ESATCOM"},
                      {"key": "espnDownloadmanager", "label": "ESPN DownloadManager"},
                      {"key": "espnRadio", "label": "ESPN Radio"}, {"key": "ezos", "label": "EZOS"},
                      {"key": "edge", "label": "Edge"}, {"key": "edgeMobile", "label": "Edge Mobile"},
                      {"key": "electron", "label": "Electron"},
                      {"key": "elementBrowser", "label": "Element Browser"},
                      {"key": "elluminateLive", "label": "Elluminate Live"},
                      {"key": "elmediaPlayer", "label": "Elmedia Player"},
                      {"key": "emacs/w3", "label": "Emacs/W3"}, {"key": "epic", "label": "Epic"},
                      {"key": "epiphany", "label": "Epiphany"},
                      {"key": "espialTvBrowser", "label": "Espial TV Browser"},
                      {"key": "eudora", "label": "Eudora"}, {"key": "eudoraOse", "label": "Eudora OSE"},
                      {"key": "eudoraweb", "label": "EudoraWeb"},
                      {"key": "evernoteApp", "label": "Evernote App"},
                      {"key": "evolution", "label": "Evolution"}, {"key": "excel", "label": "Excel"},
                      {"key": "exoplayerdemo", "label": "ExoPlayerDemo"},
                      {"key": "extras4imovie", "label": "Extras4iMovie"}, {"key": "fly", "label": "FLY"},
                      {"key": "facebookApp", "label": "Facebook App"},
                      {"key": "facebookGroups", "label": "Facebook Groups"},
                      {"key": "facebookMessenger", "label": "Facebook Messenger"},
                      {"key": "facebookPagesAdmin", "label": "Facebook Pages Admin"},
                      {"key": "fancymusic", "label": "FancyMusic"},
                      {"key": "fastbrowser", "label": "FastBrowser"},
                      {"key": "feeddlerRssReader", "label": "Feeddler RSS Reader"},
                      {"key": "fennec", "label": "Fennec"}, {"key": "firebird", "label": "Firebird"},
                      {"key": "firefox", "label": "Firefox"},
                      {"key": "firefoxFocus", "label": "Firefox Focus"},
                      {"key": "firefoxForIos", "label": "Firefox for iOS"},
                      {"key": "flipboardApp", "label": "Flipboard App"},
                      {"key": "flixsterApp", "label": "Flixster App"}, {"key": "flock", "label": "Flock"},
                      {"key": "fluid", "label": "Fluid"}, {"key": "flyflow", "label": "FlyFlow"},
                      {"key": "fossamail", "label": "FossaMail"}, {"key": "foxconn", "label": "Foxconn"},
                      {"key": "framabird", "label": "Framabird"},
                      {"key": "free-podcasts", "label": "Free-Podcasts"},
                      {"key": "freeboxBrowser", "label": "Freebox Browser"},
                      {"key": "frontpage", "label": "FrontPage"}, {"key": "geo", "label": "GEO"},
                      {"key": "gspda", "label": "GSPDA"}, {"key": "gsmart", "label": "GSmart"},
                      {"key": "galeon", "label": "Galeon"}, {"key": "goldenpod", "label": "GoldenPod"},
                      {"key": "goodreader", "label": "GoodReader"},
                      {"key": "googleApp", "label": "Google App"},
                      {"key": "googleDesktop", "label": "Google Desktop"},
                      {"key": "googleEarth", "label": "Google Earth"},
                      {"key": "googleMail", "label": "Google Mail"},
                      {"key": "google+App", "label": "Google+ App"},
                      {"key": "hpSecureWebBrowser", "label": "HP Secure Web Browser"},
                      {"key": "hs", "label": "HS"}, {"key": "haier", "label": "Haier"},
                      {"key": "headlessChrome", "label": "Headless Chrome"},
                      {"key": "hitpad", "label": "Hitpad"},
                      {"key": "hotHdWallpapers", "label": "Hot HD Wallpapers"},
                      {"key": "hotWallpapers", "label": "Hot Wallpapers"},
                      {"key": "huawei", "label": "Huawei"}, {"key": "hyundai", "label": "Hyundai"},
                      {"key": "iac", "label": "IAC"}, {"key": "ibrowse", "label": "IBrowse"},
                      {"key": "ie", "label": "IE"}, {"key": "iemobile", "label": "IEMobile"},
                      {"key": "inno", "label": "INNO"}, {"key": "ixi", "label": "IXI"},
                      {"key": "icecat", "label": "IceCat"}, {"key": "icedragon", "label": "IceDragon"},
                      {"key": "iceape", "label": "Iceape"}, {"key": "icedove", "label": "Icedove"},
                      {"key": "iceowl", "label": "Iceowl"}, {"key": "iceweasel", "label": "Iceweasel"},
                      {"key": "imagemobile", "label": "ImageMobile"},
                      {"key": "incredimail", "label": "Incredimail"},
                      {"key": "instagramApp", "label": "Instagram App"},
                      {"key": "installatron", "label": "Installatron"},
                      {"key": "iridiumBrowser", "label": "Iridium Browser"},
                      {"key": "iron", "label": "Iron"}, {"key": "ironMobile", "label": "Iron Mobile"},
                      {"key": "juziBrowser", "label": "JUZI Browser"},
                      {"key": "jasmine", "label": "Jasmine"}, {"key": "juice", "label": "Juice"},
                      {"key": "k-meleon", "label": "K-Meleon"}, {"key": "k-ninja", "label": "K-Ninja"},
                      {"key": "kkman", "label": "KKMAN"}, {"key": "kmlite", "label": "KMLite"},
                      {"key": "kmail2", "label": "KMail2"}, {"key": "knbr680", "label": "KNBR 680"},
                      {"key": "konka", "label": "KONKA"}, {"key": "kamelioApp", "label": "Kamelio App"},
                      {"key": "kazehakase", "label": "Kazehakase"}, {"key": "keeper", "label": "Keeper"},
                      {"key": "kenshoo", "label": "Kenshoo"}, {"key": "kindle", "label": "Kindle"},
                      {"key": "kindleFire", "label": "Kindle Fire"}, {"key": "kinoma", "label": "Kinoma"},
                      {"key": "kinza", "label": "Kinza"}, {"key": "klondike", "label": "Klondike"},
                      {"key": "kodiMediaCenter", "label": "Kodi Media Center"},
                      {"key": "konqueror", "label": "Konqueror"}, {"key": "kontact", "label": "Kontact"},
                      {"key": "kuaiso", "label": "Kuaiso"}, {"key": "kurioApp", "label": "Kurio App"},
                      {"key": "lg", "label": "LG"}, {"key": "lgBrowser", "label": "LG Browser"},
                      {"key": "lenovo", "label": "Lenovo"}, {"key": "libreoffice", "label": "LibreOffice"},
                      {"key": "light", "label": "Light"}, {"key": "lightning", "label": "Lightning"},
                      {"key": "lineApp", "label": "Line App"}, {"key": "links", "label": "Links"},
                      {"key": "listiaApp", "label": "Listia App"},
                      {"key": "lotusNotes", "label": "Lotus Notes"},
                      {"key": "lovenseBrowser", "label": "Lovense Browser"},
                      {"key": "lunascape", "label": "Lunascape"},
                      {"key": "lycorisDesktop/lx", "label": "Lycoris Desktop/LX"},
                      {"key": "lync", "label": "Lync"}, {"key": "lynx", "label": "Lynx"},
                      {"key": "m3gate", "label": "M3Gate"},
                      {"key": "mauiWapBrowser", "label": "MAUI Wap Browser"},
                      {"key": "mplayer", "label": "MPlayer"},
                      {"key": "mstarBrowser", "label": "MStar Browser"},
                      {"key": "macappstore", "label": "MacAppStore"},
                      {"key": "mailFree", "label": "Mail Free"},
                      {"key": "mailMaster", "label": "Mail Master"}, {"key": "mailbar", "label": "MailBar"},
                      {"key": "markLevinShow", "label": "Mark Levin Show"},
                      {"key": "matome", "label": "Matome"}, {"key": "maxon", "label": "Maxon"},
                      {"key": "maxthon", "label": "Maxthon"},
                      {"key": "maxthonNitro", "label": "Maxthon Nitro"},
                      {"key": "mediaPlayers", "label": "Media Players"},
                      {"key": "mediago", "label": "MediaGo"}, {"key": "mediamonkey", "label": "MediaMonkey"},
                      {"key": "mercator", "label": "Mercator"}, {"key": "mercury", "label": "Mercury"},
                      {"key": "microb", "label": "MicroB"},
                      {"key": "microsoftNetshow", "label": "Microsoft NetShow"},
                      {"key": "midori", "label": "Midori"}, {"key": "minimo", "label": "Minimo"},
                      {"key": "miro", "label": "Miro"}, {"key": "mitsuBrowser", "label": "Mitsu Browser"},
                      {"key": "miuiBrowser", "label": "Miui Browser"},
                      {"key": "mobicip", "label": "Mobicip"},
                      {"key": "mobileSafariUiwebview", "label": "Mobile Safari UIWebView"},
                      {"key": "mobileexplorer", "label": "MobileExplorer"},
                      {"key": "mobileiron", "label": "MobileIron"},
                      {"key": "mobilerss", "label": "MobileRSS"}, {"key": "mobmail", "label": "Mobmail"},
                      {"key": "modelSBrowser", "label": "Model S Browser"},
                      {"key": "mosaic", "label": "Mosaic"},
                      {"key": "motorolaInternetBrowser", "label": "Motorola Internet Browser"},
                      {"key": "mozilla", "label": "Mozilla"}, {"key": "multizilla", "label": "MultiZilla"},
                      {"key": "musicdownloader", "label": "MusicDownloader"},
                      {"key": "myInternetBrowser", "label": "My Internet Browser"},
                      {"key": "mynews", "label": "MyNews"}, {"key": "nec", "label": "NEC"},
                      {"key": "naver", "label": "Naver"}, {"key": "navigator", "label": "Navigator"},
                      {"key": "netfront", "label": "NetFront"},
                      {"key": "netfrontNx", "label": "NetFront NX"},
                      {"key": "netfrontlifebrowser", "label": "NetFrontLifeBrowser"},
                      {"key": "netpositive", "label": "NetPositive"},
                      {"key": "netvibesApp", "label": "NetVibes App"}, {"key": "netbox", "label": "Netbox"},
                      {"key": "netgemSetTopBox", "label": "Netgem Set Top Box"},
                      {"key": "netscape", "label": "Netscape"}, {"key": "neuron", "label": "Neuron"},
                      {"key": "newsarticleApp", "label": "NewsArticle App"},
                      {"key": "newsfire", "label": "NewsFire"}, {"key": "nichrome", "label": "Nichrome"},
                      {"key": "nintendoBrowser", "label": "Nintendo Browser"},
                      {"key": "nokiaBrowser", "label": "Nokia Browser"},
                      {"key": "nokiaProxyBrowser", "label": "Nokia Proxy Browser"},
                      {"key": "ntent", "label": "Ntent"}, {"key": "obigoQ", "label": "Obigo Q"},
                      {"key": "oculusBrowser", "label": "Oculus Browser"},
                      {"key": "odysseyWebBrowser", "label": "Odyssey Web Browser"},
                      {"key": "office", "label": "Office"},
                      {"key": "officeSyncproc", "label": "Office SyncProc"},
                      {"key": "officeUploadCenter", "label": "Office Upload Center"},
                      {"key": "offlinePages", "label": "Offline Pages"},
                      {"key": "oktaMobileApp", "label": "Okta Mobile App"},
                      {"key": "omniweb", "label": "OmniWeb"}, {"key": "onebrowser", "label": "OneBrowser"},
                      {"key": "onenote", "label": "OneNote"}, {"key": "openbsdFtp", "label": "OpenBSD ftp"},
                      {"key": "openoffice", "label": "OpenOffice"},
                      {"key": "openwaveMobileBrowser", "label": "Openwave Mobile Browser"},
                      {"key": "opera", "label": "Opera"}, {"key": "operaMini", "label": "Opera Mini"},
                      {"key": "operaMobile", "label": "Opera Mobile"},
                      {"key": "operaNeon", "label": "Opera Neon"}, {"key": "orca", "label": "Orca"},
                      {"key": "oregano", "label": "Oregano"}, {"key": "origin", "label": "Origin"},
                      {"key": "otter", "label": "Otter"}, {"key": "outlook", "label": "Outlook"},
                      {"key": "overcast", "label": "Overcast"},
                      {"key": "overwolfBrowser", "label": "Overwolf Browser"},
                      {"key": "perfectBrowser", "label": "PERFECT Browser"},
                      {"key": "palemoon", "label": "PaleMoon"},
                      {"key": "palmSource", "label": "Palm Source"},
                      {"key": "panasonic", "label": "Panasonic"},
                      {"key": "panasonicTvBrowser", "label": "Panasonic TV Browser"},
                      {"key": "pandora", "label": "Pandora"}, {"key": "pantech", "label": "Pantech"},
                      {"key": "peapod", "label": "Peapod"},
                      {"key": "phantomBrowser", "label": "Phantom Browser"},
                      {"key": "phantomjs", "label": "PhantomJS"}, {"key": "phoenix", "label": "Phoenix"},
                      {"key": "picCollage", "label": "Pic Collage"},
                      {"key": "pinterestApp", "label": "Pinterest App"},
                      {"key": "pirateBrowser", "label": "Pirate Browser"},
                      {"key": "player", "label": "Player"}, {"key": "playerFm", "label": "Player FM"},
                      {"key": "playstation", "label": "Playstation"},
                      {"key": "playstationBrowser", "label": "Playstation Browser"},
                      {"key": "pocketCasts", "label": "Pocket Casts"},
                      {"key": "pocketPc", "label": "Pocket PC"},
                      {"key": "pockettunes", "label": "PocketTunes"},
                      {"key": "pocomail", "label": "PocoMail"},
                      {"key": "podcruncher", "label": "PodCruncher"},
                      {"key": "podwrangler", "label": "PodWrangler"},
                      {"key": "podcastaddict", "label": "PodcastAddict"},
                      {"key": "podcastone", "label": "PodcastOne"}, {"key": "podcasts", "label": "Podcasts"},
                      {"key": "podkicker", "label": "Podkicker"},
                      {"key": "podkickerClassic", "label": "Podkicker Classic"},
                      {"key": "podkickerPro", "label": "Podkicker Pro"},
                      {"key": "polaris", "label": "Polaris"}, {"key": "polarity", "label": "Polarity"},
                      {"key": "postbox", "label": "Postbox"}, {"key": "powerpoint", "label": "PowerPoint"},
                      {"key": "powertv", "label": "PowerTV"}, {"key": "prince", "label": "Prince"},
                      {"key": "prism", "label": "Prism"}, {"key": "prismaticApp", "label": "Prismatic App"},
                      {"key": "puffin", "label": "Puffin"}, {"key": "qqbrowser", "label": "QQBrowser"},
                      {"key": "qqbrowserMini", "label": "QQBrowser Mini"},
                      {"key": "qiyuBrowser", "label": "Qiyu Browser"}, {"key": "qt", "label": "Qt"},
                      {"key": "qtwebengine", "label": "QtWebEngine"},
                      {"key": "qtwebkit", "label": "QtWebkit"}, {"key": "quicklook", "label": "QuickLook"},
                      {"key": "quicknews", "label": "QuickNews"}, {"key": "quicktime", "label": "QuickTime"},
                      {"key": "quicktimeAgent", "label": "QuickTime Agent"},
                      {"key": "quiteRss", "label": "Quite RSS"}, {"key": "quoraApp", "label": "Quora App"},
                      {"key": "qupzilla", "label": "QupZilla"},
                      {"key": "qwordBrowser", "label": "Qword Browser"}, {"key": "rma", "label": "RMA"},
                      {"key": "rssradio", "label": "RSSRadio"}, {"key": "radio", "label": "Radio"},
                      {"key": "raptr", "label": "Raptr"}, {"key": "readability", "label": "Readability"},
                      {"key": "realplayer", "label": "RealPlayer"},
                      {"key": "realplayerDownloader", "label": "RealPlayer Downloader"},
                      {"key": "rebelmouse", "label": "RebelMouse"},
                      {"key": "redflagdealsMobileApp", "label": "RedFlagDeals Mobile App"},
                      {"key": "redditApp", "label": "Reddit App"}, {"key": "reeder", "label": "Reeder"},
                      {"key": "relaxMelodies", "label": "Relax Melodies"},
                      {"key": "replay", "label": "Replay"},
                      {"key": "robloxStudio", "label": "Roblox Studio"},
                      {"key": "roccat", "label": "Roccat"}, {"key": "rockmelt", "label": "RockMelt"},
                      {"key": "rockyChatworkMobile", "label": "Rocky ChatWork Mobile"},
                      {"key": "rokuDvp", "label": "Roku DVP"}, {"key": "semc", "label": "SEMC"},
                      {"key": "safari", "label": "Safari"}, {"key": "sagem", "label": "Sagem"},
                      {"key": "sailfishBrowser", "label": "Sailfish Browser"},
                      {"key": "saina", "label": "Saina"}, {"key": "salamBrowser", "label": "Salam Browser"},
                      {"key": "salesforceApp", "label": "SalesForce App"},
                      {"key": "samsung", "label": "Samsung"},
                      {"key": "samsungBrowser", "label": "Samsung Browser"},
                      {"key": "samsungCrossapp", "label": "Samsung CrossApp"},
                      {"key": "samsungMobileBrowser", "label": "Samsung Mobile Browser"},
                      {"key": "samsungTv", "label": "Samsung TV"},
                      {"key": "samsungWebview", "label": "Samsung WebView"},
                      {"key": "sandvox", "label": "Sandvox"},
                      {"key": "schoolwiresApp", "label": "Schoolwires App"},
                      {"key": "seamonkey", "label": "SeaMonkey"},
                      {"key": "secondLifeCommerceClient", "label": "Second Life Commerce Client"},
                      {"key": "secondlife", "label": "SecondLife"},
                      {"key": "seznamBrowser", "label": "Seznam Browser"},
                      {"key": "sharp", "label": "Sharp"}, {"key": "shiira", "label": "Shiira"},
                      {"key": "shrook", "label": "Shrook"}, {"key": "silk", "label": "Silk"},
                      {"key": "sitecon", "label": "SiteCon"}, {"key": "skyfire", "label": "Skyfire"},
                      {"key": "skykid", "label": "Skykid"}, {"key": "sleipnir", "label": "Sleipnir"},
                      {"key": "slimboat", "label": "SlimBoat"},
                      {"key": "slimbrowser", "label": "SlimBrowser"},
                      {"key": "slimjetBrowser", "label": "SlimJet Browser"},
                      {"key": "slimerjs", "label": "SlimerJS"},
                      {"key": "smarttvWebbrowser", "label": "SmartTV WebBrowser"},
                      {"key": "smartviera", "label": "SmartViera"}, {"key": "snapchat", "label": "Snapchat"},
                      {"key": "snowtape", "label": "Snowtape"},
                      {"key": "sogouExplorer", "label": "Sogou Explorer"},
                      {"key": "sogouMobile", "label": "Sogou Mobile"},
                      {"key": "sohunewsApp", "label": "SohuNews App"},
                      {"key": "songbirdApp", "label": "Songbird App"}, {"key": "sony", "label": "Sony"},
                      {"key": "sonyPs2", "label": "Sony PS2"}, {"key": "sonyPsp", "label": "Sony PSP"},
                      {"key": "soundcloudApp", "label": "SoundCloud App"},
                      {"key": "sparrow", "label": "Sparrow"}, {"key": "spector", "label": "Spector"},
                      {"key": "sportsTalk1050", "label": "Sports Talk 1050"},
                      {"key": "spotify", "label": "Spotify"},
                      {"key": "sputnikBrowser", "label": "Sputnik Browser"},
                      {"key": "sraf", "label": "Sraf"}, {"key": "stainless", "label": "Stainless"},
                      {"key": "startBrowser", "label": "Start Browser"}, {"key": "steam", "label": "Steam"},
                      {"key": "steamBigPicture", "label": "Steam Big Picture"},
                      {"key": "steamOverlay", "label": "Steam Overlay"},
                      {"key": "stitcher", "label": "Stitcher"},
                      {"key": "streamingPlayer", "label": "Streaming Player"},
                      {"key": "sundance", "label": "Sundance"}, {"key": "sunrise", "label": "Sunrise"},
                      {"key": "superbird", "label": "SuperBird"},
                      {"key": "surfBrowser", "label": "Surf Browser"}, {"key": "swing", "label": "Swing"},
                      {"key": "symphonyBrowser", "label": "Symphony Browser"},
                      {"key": "twcSportsnet", "label": "TWC SportsNet"},
                      {"key": "tazweb", "label": "TazWeb"}, {"key": "teleca-obigo", "label": "Teleca-Obigo"},
                      {"key": "tenfourfox", "label": "TenFourFox"},
                      {"key": "tentaBrowser", "label": "Tenta Browser"}, {"key": "terra", "label": "Terra"},
                      {"key": "teslabrowser", "label": "TeslaBrowser"}, {"key": "tevion", "label": "Tevion"},
                      {"key": "theBat!", "label": "The Bat!"},
                      {"key": "theDanPatrickShow", "label": "The Dan Patrick Show"},
                      {"key": "theDiary", "label": "The Diary"}, {"key": "theworld", "label": "TheWorld"},
                      {"key": "thunderbird", "label": "Thunderbird"},
                      {"key": "tinybrowser", "label": "TinyBrowser"},
                      {"key": "tizenBrowser", "label": "Tizen Browser"},
                      {"key": "toppodcasts", "label": "TopPodcasts"}, {"key": "tubetv", "label": "TubeTV"},
                      {"key": "tungstenBrowser", "label": "Tungsten Browser"},
                      {"key": "tweetbot", "label": "Tweetbot"},
                      {"key": "twitterApp", "label": "Twitter App"},
                      {"key": "ucBrowser", "label": "UC Browser"},
                      {"key": "ucBrowserHd", "label": "UC Browser HD"},
                      {"key": "ucBrowserMini", "label": "UC Browser Mini"},
                      {"key": "urBrowser", "label": "UR Browser"},
                      {"key": "vlcMediaPlayer", "label": "VLC Media Player"},
                      {"key": "vmsMosaic", "label": "VMS Mosaic"},
                      {"key": "voxMusicPlayer", "label": "VOX Music Player"},
                      {"key": "vanillasurf", "label": "VanillaSurf"}, {"key": "vienna", "label": "Vienna"},
                      {"key": "visio", "label": "Visio"}, {"key": "vitelcom", "label": "Vitelcom"},
                      {"key": "vivaldi", "label": "Vivaldi"},
                      {"key": "vmwareBrowser", "label": "VmWare Browser"},
                      {"key": "vodafone", "label": "Vodafone"}, {"key": "vonkeror", "label": "Vonkeror"},
                      {"key": "voyager", "label": "Voyager"}, {"key": "wapBrowser", "label": "WAP Browser"},
                      {"key": "wkbrowser", "label": "WKBrowser"},
                      {"key": "wahooBrowser", "label": "Wahoo Browser"},
                      {"key": "waterfox", "label": "Waterfox"}, {"key": "wechatApp", "label": "WeChat App"},
                      {"key": "wetabBrowser", "label": "WeTab Browser"},
                      {"key": "webclipApp", "label": "WebClip App"},
                      {"key": "webkit/webos", "label": "WebKit/webOS"},
                      {"key": "webpirateBrowser", "label": "WebPirate Browser"},
                      {"key": "webtv/msntv", "label": "WebTV/MSNTV"},
                      {"key": "webthumb", "label": "WebThumb"}, {"key": "weibo", "label": "Weibo"},
                      {"key": "whaleBrowser", "label": "Whale Browser"},
                      {"key": "whatsapp", "label": "WhatsApp"},
                      {"key": "whitehatAviator", "label": "WhiteHat Aviator"},
                      {"key": "winamp", "label": "WinAmp"}, {"key": "winwap", "label": "WinWAP"},
                      {"key": "windowsLiveMail", "label": "Windows Live Mail"},
                      {"key": "windowsMediaPlayer", "label": "Windows Media Player"},
                      {"key": "windowsPowershell", "label": "Windows PowerShell"},
                      {"key": "windows-update-agent", "label": "Windows-Update-Agent"},
                      {"key": "wireApp", "label": "Wire App"}, {"key": "word", "label": "Word"},
                      {"key": "wordpressApp", "label": "WordPress App"}, {"key": "wyzo", "label": "Wyzo"},
                      {"key": "yoloBrowser", "label": "YOLO Browser"}, {"key": "yaapp", "label": "YaApp"},
                      {"key": "yahooMailMobile", "label": "Yahoo Mail Mobile"},
                      {"key": "yahooMessenger", "label": "Yahoo Messenger"},
                      {"key": "yahooMobileApp", "label": "Yahoo Mobile App"},
                      {"key": "yahoo!App", "label": "Yahoo! App"},
                      {"key": "yandexBrowser", "label": "Yandex Browser"},
                      {"key": "yandexSearch", "label": "Yandex Search"},
                      {"key": "yellowpagesMobileApp", "label": "YellowPages Mobile App"},
                      {"key": "youwaveAndroidOnPc", "label": "YouWave Android on PC"},
                      {"key": "zte", "label": "ZTE"}, {"key": "zetakeyBrowser", "label": "Zetakey Browser"},
                      {"key": "zimbraDesktop", "label": "Zimbra Desktop"}, {"key": "zune", "label": "Zune"},
                      {"key": "zvu", "label": "Zvu"}, {"key": "akregator", "label": "akregator"},
                      {"key": "bpod", "label": "bPod"},
                      {"key": "billigfluegefinalApp", "label": "billigFluegeFinal App"},
                      {"key": "bumblebee", "label": "bumblebee"}, {"key": "ccwap", "label": "ccWAP"},
                      {"key": "doubanApp", "label": "douban App"}, {"key": "fantomas", "label": "fantomas"},
                      {"key": "fantomasCloakbrowser", "label": "fantomas cloakBrowser"},
                      {"key": "fantomasFantombrowser", "label": "fantomas fantomBrowser"},
                      {"key": "fantomasFantomcrewBrowser", "label": "fantomas fantomCrew Browser"},
                      {"key": "fantomasMultiblockerBrowser", "label": "fantomas multiBlocker browser"},
                      {"key": "fantomasShadowmakerBrowser", "label": "fantomas shadowMaker Browser"},
                      {"key": "fantomasStealthbrowser", "label": "fantomas stealthBrowser"},
                      {"key": "fgbrowser", "label": "fgBrowser"},
                      {"key": "foobar2000", "label": "foobar2000"}, {"key": "gpodder", "label": "gPodder"},
                      {"key": "i-mobile", "label": "i-mobile"},
                      {"key": "i-modeBrowser", "label": "i-mode Browser"},
                      {"key": "iball", "label": "iBall"}, {"key": "ibooksAuthor", "label": "iBooks Author"},
                      {"key": "ibrowser", "label": "iBrowser"}, {"key": "icab", "label": "iCab"},
                      {"key": "icabMobile", "label": "iCab Mobile"},
                      {"key": "ilunascape", "label": "iLunascape"},
                      {"key": "iosDataaccessd", "label": "iOS dataaccessd"},
                      {"key": "iphoneSimulator", "label": "iPhone Simulator"},
                      {"key": "ipick", "label": "iPick"}, {"key": "ipodder", "label": "iPodder"},
                      {"key": "isearch", "label": "iSearch"}, {"key": "isilox", "label": "iSiloX"},
                      {"key": "itunes", "label": "iTunes"}, {"key": "iweb", "label": "iWeb"},
                      {"key": "jbrowser", "label": "jBrowser"}, {"key": "jpodder", "label": "jPodder"},
                      {"key": "jigBrowserWeb", "label": "jig browser web"},
                      {"key": "kejian", "label": "kejian"}, {"key": "kioclient", "label": "kioclient"},
                      {"key": "lftp", "label": "lftp"}, {"key": "liebao", "label": "liebao"},
                      {"key": "lolifox", "label": "lolifox"}, {"key": "luakit", "label": "luakit"},
                      {"key": "noadsbrowser", "label": "noadsbrowser"},
                      {"key": "open-webkit-sharp", "label": "open-webkit-sharp"},
                      {"key": "phantomas", "label": "phantomas"},
                      {"key": "philpodder", "label": "philpodder"}, {"key": "podracer", "label": "podracer"},
                      {"key": "qutebrowser", "label": "qutebrowser"}, {"key": "rekonq", "label": "rekonq"},
                      {"key": "stagefright", "label": "stagefright"}, {"key": "vobsub", "label": "vobsub"},
                      {"key": "w3m", "label": "w3m"}, {"key": "wkhtmltoimage", "label": "wkhtmltoimage"},
                      {"key": "wkhtmltopdf", "label": "wkhtmltopdf"}]}
            ]
